gradle.beforeProject { app ->
 app.plugins.withId('com.android.application') {
  def base = new File(app.rootProject.projectDir, '../tools/evaluation/document-formats')
  app.android.sourceSets.androidTest.java.srcDirs += [new File(base, 'tests')]
  app.android.sourceSets.androidTest.manifest.srcFile(new File(base, 'AndroidManifest.xml'))
 }
}
