#!/usr/bin/env python3
"""Normalize repeated shard names in a new alias database; verify every logical row."""
import argparse,json,pathlib,resource,sqlite3,time
from acquire import atomic,digest
p=argparse.ArgumentParser();p.add_argument('source');p.add_argument('out');a=p.parse_args();source=pathlib.Path(a.source).resolve();out=pathlib.Path(a.out).resolve()
if out.exists():raise SystemExit('Refuse to replace alias artifact')
start=time.monotonic();db=sqlite3.connect(out,uri=True);db.executescript('PRAGMA journal_mode=DELETE; PRAGMA cache_size=-262144; PRAGMA temp_store=FILE; PRAGMA threads=0; CREATE TABLE shard_names(id INTEGER PRIMARY KEY,name TEXT NOT NULL UNIQUE); CREATE TABLE aliases(alias TEXT NOT NULL,target INTEGER NOT NULL,shard INTEGER NOT NULL REFERENCES shard_names(id),fragment TEXT NOT NULL,PRIMARY KEY(alias,target,fragment)) WITHOUT ROWID; CREATE TABLE metadata(key TEXT PRIMARY KEY,value TEXT NOT NULL) WITHOUT ROWID;');db.execute('ATTACH DATABASE ? AS original',(f'file:{source}?mode=ro&immutable=1',));db.execute('PRAGMA original.cache_size=-65536')
for i,(name,) in enumerate(db.execute('SELECT DISTINCT shard FROM original.aliases ORDER BY shard').fetchall()):db.execute('INSERT INTO shard_names VALUES (?,?)',(i,name))
db.execute('INSERT INTO aliases SELECT a.alias,a.target,n.id,a.fragment FROM original.aliases a JOIN shard_names n ON n.name=a.shard');db.commit();bad=db.execute('SELECT count(*) FROM aliases a LEFT JOIN shard_names n ON n.id=a.shard LEFT JOIN original.aliases o ON o.alias=a.alias AND o.target=a.target AND o.fragment=a.fragment WHERE n.id IS NULL OR o.alias IS NULL OR o.shard!=n.name').fetchone()[0];old_count=db.execute('SELECT count(*) FROM original.aliases').fetchone()[0];count=db.execute('SELECT count(*) FROM aliases').fetchone()[0];assert bad==0 and count==old_count
source_hash=digest(source);db.executemany('INSERT INTO metadata VALUES (?,?)',[('schema','2'),('parent_sha256',source_hash),('mapping','Every reconstructed alias/target/shard-name/fragment equals its parent row')]);db.commit();integrity=db.execute('PRAGMA integrity_check').fetchone()[0];assert integrity=='ok';db.close();result={'schema':2,'source':str(source),'source_sha256':source_hash,'source_bytes':source.stat().st_size,'bytes':out.stat().st_size,'sha256':digest(out),'aliases':count,'logical_row_mismatches':bad,'sqlite_integrity':integrity,'seconds':time.monotonic()-start,'peak_rss_kib':resource.getrusage(resource.RUSAGE_SELF).ru_maxrss,'change':'Repeated shard filename replaced with integer reference; no alias, target, fragment or source facts removed'};atomic(out.with_suffix(out.suffix+'.json'),result);print(json.dumps(result,indent=2))
