"""One-time public development query freeze; expected titles are source locators, not answer gold."""
import hashlib,json,pathlib,datetime
head=['Earth','Sun','Moon','Water','Oxygen','Carbon','Photosynthesis','Gravity','Evolution','Democracy','World War II','Internet','Computer','DNA','Solar System','Climate change']
tail=['10th Tank Corps','Transport in Belgium','Futurist cooking','Museum Plaza','Acanthostega','Brachistochrone curve','Cahokia','Antikythera mechanism','Oklo','Lake Nyos','Pando (tree)','Socotra','Zhang Heng','Srinivasa Ramanujan','Tardigrade','Axolotl']
para=[('distance from zero','Absolute value'),('plants convert sunlight into chemical energy','Photosynthesis'),('water vapor turns into liquid','Condensation'),('liquid water changes into vapor','Evaporation'),('ground shakes when rocks release energy','Earthquake'),('molten rock below the surface','Magma'),('electric resistance voltage and current',"Ohm's law"),('hereditary information in living organisms','DNA'),('acid donates a proton','Brønsted–Lowry acid–base theory'),('foods prepared using heat','Cooking'),('organisms change over generations','Evolution'),('landmass movement across geological time','Plate tectonics'),('ocean water rises and falls periodically','Tide'),('cell division two identical daughter cells','Mitosis'),('light bends between different materials','Refraction'),('heat flows without material movement','Thermal conduction')]
math=[('Pythagorean theorem hypotenuse squared','Pythagorean theorem'),('Speed of light metres per second','Speed of light'),('Gravitational constant units','Gravitational constant'),('Planck constant joule seconds','Planck constant'),('Ideal gas law pressure volume temperature','Ideal gas law'),("Newton second law force mass acceleration","Newton's laws of motion"),('Kinetic energy one half mass velocity squared','Kinetic energy'),('Quadratic formula discriminant','Quadratic formula'),('Euler identity exponential pi','Euler\'s identity'),('Mass energy equivalence c squared','Mass–energy equivalence'),('Celsius Kelvin temperature conversion','Celsius'),('Sphere volume radius cubed','Sphere'),('Circle circumference diameter pi','Circle'),('Density mass volume units','Density'),('Pressure pascal units','Pressure'),('Avogadro constant reciprocal mole','Avogadro constant')]
multi=[('evaporation condensation phase change',['Evaporation','Condensation']),('Earth Moon radius',['Earth','Moon']),('mitosis meiosis cell division',['Mitosis','Meiosis']),('conduction convection heat transfer',['Thermal conduction','Convection']),('oxygen carbon atomic number',['Oxygen','Carbon']),('magma lava location',['Magma','Lava']),('solar wind magnetic field',['Solar wind','Magnetic field']),('acid base proton',['Acid','Base (chemistry)'])]
absent=['PocketLore secret launch code zqxv915','Museum Plaza restaurant opening hours October 2099','current weather tomorrow Socotra 2099','exact population of Mars in year 2300','unpublished password for Einstein private mailbox','florbnax energy theorem coefficient','live flight price London Tokyo next Tuesday','proven cure using imaginary element unobtainium']
out=[]
for category,items in [('head',[(x,[x]) for x in head]),('tail',[(x,[x]) for x in tail]),('paraphrase',[(q,[t]) for q,t in para]),('math_units',[(q,[t]) for q,t in math]),('multi_part',multi),('absence',[(q,[]) for q in absent])]:
 for q,t in items:out.append({'id':f'q{len(out)+1:03d}','category':category,'query':q,'expected_titles':t,'expect_answer_support':bool(t)})
p=pathlib.Path('docs/evidence/scale/wiki/queries-v1.json');assert not p.exists();p.write_text(json.dumps({'version':1,'created_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'policy':'Frozen builder development retrieval probes, not holdout or factual answer gold. Head/tail are intended topic strata, measured view ranks reported separately. Source support audited against pinned records without rewriting probes. Absence may retrieve related articles but cannot support the requested claim.','queries':out},indent=2)+'\n')
pathlib.Path('docs/evidence/scale/wiki/query-freeze.json').write_text(json.dumps({'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'count':len(out),'frozen_before':'builder/index/retrieval implementation'},indent=2)+'\n')
