#!/usr/bin/env python3
"""Derive a smaller frozen full tier without changing canonical identities or view facts."""
import argparse,json,pathlib,resource,sqlite3,time
from acquire import atomic,digest
p=argparse.ArgumentParser();p.add_argument('source');p.add_argument('out');p.add_argument('--full',type=int,required=True);a=p.parse_args();source=pathlib.Path(a.source).resolve();out=pathlib.Path(a.out).resolve()
if out.exists():raise SystemExit('Refuse to overwrite priority freeze')
start=time.monotonic();parent_hash=digest(source);db=sqlite3.connect(out,uri=True);db.executescript('PRAGMA cache_size=-262144; PRAGMA temp_store=FILE; PRAGMA threads=1; PRAGMA journal_mode=DELETE; PRAGMA synchronous=FULL;');db.execute('ATTACH DATABASE ? AS parent',(f'file:{source}?mode=ro&immutable=1',));db.execute('PRAGMA parent.cache_size=-65536');assert 0<a.full<=db.execute('SELECT sum(full) FROM parent.priority').fetchone()[0]
db.executescript('CREATE TABLE priority(id INTEGER PRIMARY KEY,title TEXT NOT NULL,shard TEXT NOT NULL,source_row INTEGER NOT NULL,views INTEGER,full INTEGER NOT NULL DEFAULT 0); INSERT INTO priority SELECT id,title,shard,source_row,views,0 FROM parent.priority; CREATE INDEX priority_order ON priority(views DESC,id ASC);');db.execute('UPDATE priority SET full=1 WHERE id IN (SELECT id FROM priority ORDER BY views DESC,id ASC LIMIT ?)',(a.full,));db.commit()
assert db.execute('SELECT count(*) FROM priority p JOIN parent.priority q USING(id) WHERE p.title!=q.title OR p.shard!=q.shard OR p.source_row!=q.source_row OR p.views IS NOT q.views').fetchone()[0]==0
result={'parent':str(source),'parent_sha256':parent_hash,'canonical_identity':'Unchanged parent page IDs, titles, source rows and observed view values; checked every derived row','ranking':'views descending, page ID ascending, unknown values last','eligible_canonical':db.execute('SELECT count(*) FROM priority').fetchone()[0],'full':a.full,'lead':db.execute('SELECT count(*) FROM priority WHERE full=0').fetchone()[0],'full_with_unknown_views':db.execute('SELECT count(*) FROM priority WHERE full=1 AND views IS NULL').fetchone()[0],'per_shard':db.execute('SELECT shard,count(*),sum(full) FROM priority GROUP BY shard').fetchall(),'integrity_check':db.execute('PRAGMA integrity_check').fetchone()[0],'seconds':time.monotonic()-start,'peak_rss_kib':resource.getrusage(resource.RUSAGE_SELF).ru_maxrss,'reason':'Budget adaptation after complete two-million-full shard measurements; aggregation interval remains unknown'};db.close();result['sha256']=digest(out);atomic(out.with_suffix('.json'),result);print(json.dumps(result,indent=2))
