package org.pocketlore.app;
import android.app.Instrumentation;import android.os.*;import java.io.*;import java.nio.file.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.concurrent.atomic.*;import org.json.*;
/** Actual library rollback, duplicate update staging, retained model and disk/memory measurements. */
public final class ReleaseRollbackInstrumentation extends Instrumentation {
 @Override public void onCreate(Bundle b){super.onCreate(b);start();}
 static long bytes(File f){if(f.isFile())return f.length();long n=0;File[] children=f.listFiles();if(children!=null)for(File c:children)n+=bytes(c);return n;}
 @Override public void onStart(){Bundle result=new Bundle();JSONObject report=new JSONObject();File files=getTargetContext().getFilesDir(),dir=new File(files,"pack-library"),catalog=new File(dir,"catalog.json"),model=new File(files,"model.gguf");try{String cat=BroadPack.hash(catalog),mod=BroadPack.hash(model);long original=bytes(files);JSONArray checks=new JSONArray();String broad="b8d18801b099402205938979ab2bb44ee9a316f06f030aab789cf93ba3605012",ref="567e9bbbaab896826809ec20f81ae1c4b3f421b011931edae0989d28cfce10ea";PackLibrary library=new PackLibrary(files);AtomicBoolean sampling=new AtomicBoolean(true);AtomicLong peak=new AtomicLong(),peakFiles=new AtomicLong(),pss=new AtomicLong();Thread sampler=new Thread(()->{while(sampling.get()){long stage=0;for(File f:Objects.requireNonNull(dir.listFiles()))if(f.getName().endsWith(".partial"))stage+=f.length();peak.accumulateAndGet(stage,Math::max);peakFiles.accumulateAndGet(bytes(files),Math::max);Debug.MemoryInfo m=new Debug.MemoryInfo();Debug.getMemoryInfo(m);pss.accumulateAndGet(m.getTotalPss(),Math::max);try{Thread.sleep(5);}catch(InterruptedException e){break;}}});sampler.start();try{
 for(String mode:new String[]{"corrupt","cancel-before","cancel-during","duplicate-retry"}){AtomicInteger polls=new AtomicInteger();long begin=SystemClock.elapsedRealtime();boolean failed=false;String error="";InputStream in;if(mode.equals("corrupt")){byte[] raw=Files.readAllBytes(new File(dir,ref+".plpack").toPath());raw[0]^=1;in=new ByteArrayInputStream(raw);}else in=new FileInputStream(new File(dir,broad+".plpack"));try(InputStream owned=in){library.install(owned,()->mode.equals("cancel-before")||mode.equals("cancel-during")&&polls.incrementAndGet()>10);}catch(Exception e){failed=true;error=e.toString();}if(failed==mode.equals("duplicate-retry"))throw new AssertionError("Unexpected rollback/retry result: "+mode+" "+error);if(!cat.equals(BroadPack.hash(catalog))||!mod.equals(BroadPack.hash(model)))throw new AssertionError("Saved catalog/model changed");if(Arrays.stream(Objects.requireNonNull(dir.list())).anyMatch(x->x.endsWith(".partial")))throw new AssertionError("Staging retained");checks.put(new JSONObject().put("case",mode).put("error",error).put("ms",SystemClock.elapsedRealtime()-begin).put("rejected",failed));}
 }finally{sampling.set(false);sampler.join();}PackLibrary.Snapshot snapshot=library.load();if(snapshot.entries.size()!=3||snapshot.engine.size()!=40891)throw new AssertionError("Library changed");report.put("checks",checks).put("installed_files_before_bytes",original).put("installed_files_after_bytes",bytes(files)).put("cache_bytes",bytes(getTargetContext().getCacheDir())).put("sampled_staging_peak_bytes",peak.get()).put("sampled_files_peak_bytes",peakFiles.get()).put("sample_interval_ms",5).put("sampled_pss_kib",pss.get()).put("model_sha256",mod).put("catalog_sha256",cat).put("proc_status",new String(Files.readAllBytes(new File("/proc/self/status").toPath()),StandardCharsets.UTF_8)).put("update_scope","Real duplicate-edition copy/retry; full edition replacement unsupported/unmeasured, no success claim").put("status","PASS");
 }catch(Throwable e){try{report.put("status","FAIL").put("error",e.toString());}catch(Exception ignored){}}try{Files.write(new File(files,"release-tests/rollback.json").toPath(),report.toString(2).getBytes(StandardCharsets.UTF_8));}catch(Exception e){result.putString("write_error",e.toString());}result.putString("report",report.toString());finish(report.optString("status").equals("PASS")?-1:1,result);}
}
