package org.pocketlore.app;
import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.net.Uri;import android.media.*;import android.widget.*;import java.io.*;import java.nio.*;import java.util.concurrent.*;
/** Optional local recognition, separate from Saved/reader/export UX. */
public final class AttachmentsActivity extends Activity{
 private final Object captureLock=new Object();private volatile long captureStarts;private final ExecutorService worker=Executors.newSingleThreadExecutor();private volatile boolean cancelled,closed,recording;private volatile Thread thread;private volatile boolean busy;private TextView status;private EditText preview;private String receipt="";private Button use;private volatile AudioRecord microphone;
 public void onCreate(Bundle state){super.onCreate(state);LinearLayout box=new LinearLayout(this);box.setOrientation(1);box.setPadding(24,24,24,24);ScrollView sc=new ScrollView(this);sc.addView(box);setContentView(sc);TextView title=new TextView(this);title.setText("Offline photo text and speech");title.setTextSize(24);box.addView(title);TextView help=new TextView(this);help.setText("Optional English recognition. Install verified local assets before use; no automatic download, cloud engine or image reasoning. Results can be wrong. Review before using as a question. Images: 4 MiB / 4 million pixels. Audio: 15 seconds, 16 kHz mono PCM WAV. Typing stays available without assets.");box.addView(help);
  add(box,"Install English OCR data",()->pick(1,"*/*"));add(box,"Install English speech model",()->pick(2,"*/*"));add(box,"Recognize photo text",()->pick(3,"image/*"));add(box,"Transcribe local WAV",()->pick(4,"audio/*"));add(box,"Record speech",()->{if(busy)return;if(!AttachmentAssets.file(getFilesDir(),true).exists()){show("Local speech model absent. Typing remains available; no microphone started.");return;}if(checkSelfPermission(android.Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{android.Manifest.permission.RECORD_AUDIO},5);else record();});add(box,"Stop recording",()->recording=false);add(box,"Cancel recognition",()->cancel());preview=new EditText(this);preview.setHint("Recognized text — review and edit");preview.setMinLines(3);box.addView(preview);use=add(box,"Use reviewed text as question",()->{if(busy||preview.getText().toString().trim().isEmpty())return;Intent result=new Intent().putExtra("recognized_text",preview.getText().toString()).putExtra("recognition_receipt",receipt+"\nUser-reviewed text SHA-256: "+hashText(preview.getText().toString()));setResult(RESULT_OK,result);finish();});use.setEnabled(false);add(box,"Return without attachment",()->{cancel();finish();});status=new TextView(this);status.setText("No recognition requested. Models are optional and never downloaded by the app.");status.setTextIsSelectable(true);box.addView(status);
 }
 static String hashText(String s){try{return KnowledgePack.hash(s.getBytes(java.nio.charset.StandardCharsets.UTF_8));}catch(Exception e){throw new IllegalStateException(e);}}
 Button add(LinearLayout box,String title,Runnable action){Button b=new Button(this);b.setText(title);box.addView(b);b.setOnClickListener(v->action.run());return b;}
 void pick(int code,String type){if(!busy)startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType(type).addCategory(Intent.CATEGORY_OPENABLE).putExtra(Intent.EXTRA_LOCAL_ONLY,true),code);}
 interface Work{void run()throws Exception;}
 void work(Work w){if(busy)return;busy=true;cancelled=false;use.setEnabled(false);preview.setText("");receipt="";worker.execute(()->{thread=Thread.currentThread();try{w.run();}catch(Exception|OutOfMemoryError e){show("Stopped: "+e.getMessage()+". No recognition was submitted.");}finally{thread=null;Thread.interrupted();runOnUiThread(()->{if(!closed){busy=false;use.setEnabled(!preview.getText().toString().trim().isEmpty());}});}});}
 void show(String s){runOnUiThread(()->{if(!closed)status.setText(s);});}
 void recognized(AttachmentEngine.Result r){runOnUiThread(()->{if(!closed&&!cancelled){receipt=r.receipt;preview.setText(r.text);status.setText(r.text.isEmpty()?"No text or speech recognized. Try clearer input; nothing was invented.":"Recognized input — check every word before use.\n"+r.receipt);}});}
 protected void onActivityResult(int code,int result,Intent data){super.onActivityResult(code,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;Uri uri=data.getData();work(()->{try(InputStream in=DocumentInput.open(getContentResolver(),uri,()->cancelled||closed)){if(code==1||code==2){show("Verifying optional local asset…");AttachmentAssets.install(getFilesDir(),code==2,in,()->cancelled||closed);show("Verified optional asset installed locally.");}else{byte[] raw=PersonalDocuments.read(in,code==3?4*1024*1024:512000,()->cancelled||closed);show("Recognizing locally…");recognized(code==3?AttachmentEngine.image(getFilesDir(),raw,uri.toString(),()->cancelled||closed):AttachmentEngine.audio(getFilesDir(),raw,uri.toString(),()->cancelled||closed));}}});}
 public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==5){if(g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)record();else show("Microphone permission denied. Type or choose a local WAV instead.");}}
 void record(){work(()->{if(!AttachmentAssets.available(getFilesDir(),true))throw new IOException("Local speech model absent; typing remains available");int min=AudioRecord.getMinBufferSize(16000,AudioFormat.CHANNEL_IN_MONO,AudioFormat.ENCODING_PCM_16BIT);if(min<=0)throw new IOException("Microphone format unavailable");PersonalText.check(()->cancelled||closed);AudioRecord recorder; synchronized(captureLock){PersonalText.check(()->cancelled||closed);recorder=new AudioRecord(MediaRecorder.AudioSource.MIC,16000,AudioFormat.CHANNEL_IN_MONO,AudioFormat.ENCODING_PCM_16BIT,Math.max(min,8192));microphone=recorder;}ByteArrayOutputStream pcm=new ByteArrayOutputStream();try{if(recorder.getState()!=AudioRecord.STATE_INITIALIZED)throw new IOException("Microphone unavailable");synchronized(captureLock){PersonalText.check(()->cancelled||closed);recorder.startRecording();captureStarts++;recording=true;}show("Recording locally — tap Stop recording, or Cancel. Maximum 15 seconds.");byte[] buffer=new byte[2048];long end=SystemClock.elapsedRealtime()+15000;while(recording&&!cancelled&&!closed&&pcm.size()<480000&&SystemClock.elapsedRealtime()<end){int n=recorder.read(buffer,0,Math.min(buffer.length,480000-pcm.size()),AudioRecord.READ_NON_BLOCKING);if(n<0)throw new IOException("Microphone read failed");if(n>0)pcm.write(buffer,0,n);else Thread.sleep(10);}}finally{recording=false;try{recorder.stop();}catch(Exception ignored){}recorder.release();microphone=null;}PersonalText.check(()->cancelled||closed);show("Transcribing local recording…");recognized(AttachmentEngine.audio(getFilesDir(),wave(pcm.toByteArray()),"microphone capture; original not retained",()->cancelled||closed));});}
 static byte[] wave(byte[] pcm){ByteBuffer b=ByteBuffer.allocate(pcm.length+44).order(ByteOrder.LITTLE_ENDIAN);b.putInt(0x46464952).putInt(pcm.length+36).putInt(0x45564157).putInt(0x20746d66).putInt(16).putShort((short)1).putShort((short)1).putInt(16000).putInt(32000).putShort((short)2).putShort((short)16).putInt(0x61746164).putInt(pcm.length).put(pcm);return b.array();}
 void cancel(){synchronized(captureLock){cancelled=true;recording=false;}Thread job=thread;if(job!=null){job.interrupt();AttachmentEngine.cancel(job);}runOnUiThread(()->{if(!closed){receipt="";preview.setText("");use.setEnabled(false);status.setText("Cancelled. No recognized input will be submitted.");}});}
 protected void onStop(){if(busy)cancel();super.onStop();}
 protected void onDestroy(){closed=true;cancel();worker.shutdownNow();super.onDestroy();}
}
