package org.pocketlore.app;
import android.graphics.*;import java.io.*;import java.nio.*;import java.util.function.BooleanSupplier;
/** Recognition is fallible input, never cited evidence or image reasoning. */
final class AttachmentEngine {
 static final java.util.concurrent.locks.ReentrantLock JOB=new java.util.concurrent.locks.ReentrantLock();
 private static volatile Thread activeThread;
 static void cancel(Thread owner){if(activeThread==owner)AttachmentNative.cancel();}
 static final class Result {final String text,receipt;Result(String t,String r){text=t;receipt=r;}}
 static Result image(File root,byte[] raw,String location,BooleanSupplier cancel)throws Exception{
  JOB.lockInterruptibly();try{activeThread=Thread.currentThread();PersonalText.check(cancel);AttachmentNative.reset();if(!AttachmentAssets.available(root,false))throw new IOException("English OCR data absent or changed; install the optional pinned asset first");if(raw.length>4*1024*1024)throw new IOException("Image exceeds4MiB");BitmapFactory.Options bounds=new BitmapFactory.Options();bounds.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(raw,0,raw.length,bounds);if(bounds.outWidth<=0||bounds.outHeight<=0||(long)bounds.outWidth*bounds.outHeight>4000000)throw new IOException("Image must decode to at most4million pixels");PersonalText.check(cancel);Bitmap image=BitmapFactory.decodeByteArray(raw,0,raw.length);if(image==null)throw new IOException("Cannot decode image");String text;try{int w=image.getWidth(),h=image.getHeight();byte[] gray=new byte[w*h];int[] row=new int[w];for(int y=0;y<h;y++){PersonalText.check(cancel);image.getPixels(row,0,w,0,y,w,1);for(int x=0;x<w;x++){int color=row[x],a=Color.alpha(color);int luminance=(77*Color.red(color)+150*Color.green(color)+29*Color.blue(color))>>8;gray[y*w+x]=(byte)((luminance*a+255*(255-a))/255);}}PersonalText.check(cancel);text=AttachmentNative.ocr(AttachmentAssets.file(root,false).getParent(),gray,w,h);}finally{image.recycle();}PersonalText.check(cancel);return result(text,raw,location,"OCR recognized text; not image reasoning",AttachmentAssets.OCR);
  }finally{activeThread=null;JOB.unlock();}
 }
 static float[] wav(byte[] raw)throws IOException{if(raw.length<44||raw.length>512000)throw new IOException("Choose a PCM WAV recording of at most15 seconds");ByteBuffer b=ByteBuffer.wrap(raw).order(ByteOrder.LITTLE_ENDIAN);if(b.getInt()!=0x46464952||Integer.toUnsignedLong(b.getInt())+8!=raw.length||b.getInt()!=0x45564157)throw new IOException("Invalid WAV container");boolean format=false;float[] pcm=null;while(b.remaining()>=8){int id=b.getInt(),size=b.getInt();if(size<0||size>b.remaining())throw new IOException("Truncated WAV chunk");int end=b.position()+size;if(id==0x20746d66){if(size<16||b.getShort()!=1||b.getShort()!=1||b.getInt()!=16000||b.getInt()!=32000||b.getShort()!=2||b.getShort()!=16)throw new IOException("WAV requires16kHz mono16-bit PCM");format=true;}else if(id==0x61746164){if(pcm!=null||size<3200||size>480000||size%2!=0)throw new IOException("Audio length rejected");pcm=new float[size/2];for(int i=0;i<pcm.length;i++)pcm[i]=b.getShort()/32768f;}b.position(end);if((size&1)!=0){if(!b.hasRemaining())throw new IOException("Missing WAV pad");b.get();}}if(!format||pcm==null||b.hasRemaining())throw new IOException("Incomplete WAV");return pcm;}
 static Result audio(File root,byte[] raw,String location,BooleanSupplier cancel)throws Exception{
  JOB.lockInterruptibly();try{activeThread=Thread.currentThread();PersonalText.check(cancel);AttachmentNative.reset();if(!AttachmentAssets.available(root,true))throw new IOException("Local English speech model absent or changed; typing remains available");float[] pcm=wav(raw);double energy=0;for(float v:pcm)energy+=v*v;String text="";if(Math.sqrt(energy/pcm.length)>=0.008){PersonalText.check(cancel);text=AttachmentNative.speech(AttachmentAssets.file(root,true).getPath(),pcm);}PersonalText.check(cancel);return result(text,raw,location,"Speech transcription; review names and numbers; noise may be mistranscribed",AttachmentAssets.SPEECH);
  }finally{activeThread=null;JOB.unlock();}
 }
 static Result result(String text,byte[] raw,String location,String kind,String hash)throws Exception{String t=text==null?"":text.trim();if(t.length()>16000)throw new IOException("Recognition output exceeds16000 UTF-16 units");return new Result(t,kind+"\nOriginal location: "+location+"\nOriginal SHA-256: "+KnowledgePack.hash(raw)+"\nRecognized UTF-8 SHA-256: "+KnowledgePack.hash(t.getBytes(java.nio.charset.StandardCharsets.UTF_8))+"\nRecognized UTF-16 offsets: [0, "+t.length()+")\nAsset SHA-256: "+hash+"\n"+AttachmentNative.IDENTITY+"\nPersonal input; no public redistribution rights or factual support inferred.");}
}
