package org.pocketlore.app;
import android.content.Context;import java.io.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.*;import java.util.*;import org.json.*;

/** Manual, extractive references only. Never feeds the research answer controller. */
final class ComparisonStore {
 static final int MAX_BYTES=65536,MAX_COMPARISONS=32,MAX_QUOTE=1200;
 final File root;final Context context;
 ComparisonStore(Context context){this.context=context;root=new File(context.getFilesDir(),"manual-comparisons");}
 static String hash(String text)throws Exception{byte[] b=MessageDigest.getInstance("SHA-256").digest(text.getBytes(StandardCharsets.UTF_8));StringBuilder h=new StringBuilder();for(byte v:b)h.append(String.format(Locale.ROOT,"%02x",v&255));return h.toString();}
 static String identity(NotebookStore.Entry e)throws Exception{return hash(new JSONArray().put(e.id).put(e.created).put(e.kind).put(e.title).put(e.question).put(e.body).put(e.provenance).toString());}
 static String label(String s)throws IOException{if(s==null||s.trim().isEmpty()||s.length()>80||s.matches("(?s).*[\\p{Cntrl}].*"))throw new IOException("Use 1–80 visible characters for labels");return s.trim();}
 static void require(boolean b,String message)throws IOException{if(!b)throw new IOException(message);}
 JSONObject create(long left,long right)throws Exception{
  require(left!=right,"Choose two different SOURCE snapshots");JSONArray subjects=new JSONArray();try(NotebookStore store=new NotebookStore(context)){for(long id:new long[]{left,right}){NotebookStore.Entry e=store.get(id);require(e.kind.equals("source"),"Only SOURCE snapshots can be compared; saved research is not source evidence");subjects.put(new JSONObject().put("record",id).put("hash",identity(e)).put("label",e.title.length()>80?e.title.substring(0,80):e.title));}}
  return new JSONObject().put("version",1).put("id",UUID.randomUUID().toString()).put("title","Manual evidence comparison").put("subjects",subjects).put("dimensions",new JSONArray()).put("note","");
 }
 File file(String id)throws IOException{require(id!=null&&id.matches("[a-f0-9-]{36}"),"Invalid comparison identity");return new File(root,id+".json");}
 static void validate(JSONObject d)throws Exception{
  require(d.getInt("version")==1,"Unknown comparison version; saved bytes retained");label(d.getString("title"));require(d.getString("note").length()<=2000,"Personal notes are limited to 2000 characters");JSONArray s=d.getJSONArray("subjects"),rows=d.getJSONArray("dimensions");require(s.length()==2&&rows.length()<=6,"Use two subjects and at most six dimensions");
  for(int i=0;i<2;i++){JSONObject x=s.getJSONObject(i);label(x.getString("label"));require(x.getLong("record")>0&&x.getString("hash").matches("[0-9a-f]{64}"),"Invalid source reference");}
  Set<String> ids=new HashSet<>();for(int i=0;i<rows.length();i++){JSONObject row=rows.getJSONObject(i);label(row.getString("name"));require(ids.add(row.getString("id")),"Duplicate dimension identity");require(row.getJSONArray("cells").length()==2,"Invalid cell inventory");}
 }
 void save(JSONObject d)throws Exception{validate(d);byte[] bytes=d.toString().getBytes(StandardCharsets.UTF_8);require(bytes.length<=MAX_BYTES,"Comparison exceeds 64 KiB");File dst=file(d.getString("id"));synchronized(ComparisonStore.class){try(ResourceStorage.Reservation token=ResourceStorage.reserve(ResourceStorage.stagePeak(2L*MAX_BYTES))){if(!root.isDirectory()&&!root.mkdirs())throw new IOException("Comparison directory unavailable");if(!dst.exists())require(list().size()<MAX_COMPARISONS,"Comparison library is full (32); remove a comparison first");File stage=File.createTempFile("comparison-",".partial",root);try{try(FileOutputStream out=new FileOutputStream(stage)){out.write(bytes);out.getFD().sync();}Files.move(stage.toPath(),dst.toPath(),StandardCopyOption.REPLACE_EXISTING,StandardCopyOption.ATOMIC_MOVE);}finally{stage.delete();}}}}
 JSONObject load(String id)throws Exception{File f=file(id);require(f.isFile()&&f.length()<=MAX_BYTES,"Comparison missing or oversized");JSONObject d=new JSONObject(new String(Files.readAllBytes(f.toPath()),StandardCharsets.UTF_8));validate(d);require(d.getString("id").equals(id),"Comparison identity mismatch");return d;}
 List<String> list(){List<String> ids=new ArrayList<>();File[] files=root.listFiles();if(files!=null)for(File f:files)if(f.getName().matches("[a-f0-9-]{36}\\.json"))ids.add(f.getName().substring(0,36));Collections.sort(ids);return ids;}
 void remove(String id)throws Exception{Files.deleteIfExists(file(id).toPath());}
 NotebookStore.Entry source(JSONObject subject)throws Exception{try(NotebookStore store=new NotebookStore(context)){NotebookStore.Entry e=store.get(subject.getLong("record"));require(e.kind.equals("source")&&identity(e).equals(subject.getString("hash")),"Source snapshot missing or changed");return e;}}
 JSONObject bind(JSONObject subject,int start,int end)throws Exception{NotebookStore.Entry e=source(subject);require(start>=0&&end>start&&end<=e.body.length()&&end-start<=MAX_QUOTE,"Select 1–1200 UTF-16 units within the snapshot");require(!(start>0&&Character.isLowSurrogate(e.body.charAt(start)))&&!(end<e.body.length()&&Character.isLowSurrogate(e.body.charAt(end))),"Selection splits a Unicode character");return new JSONObject().put("start",start).put("end",end).put("quote",e.body.substring(start,end)).put("source_hash",subject.getString("hash"));}
 String cell(JSONObject subject,Object value){if(value==null||value==JSONObject.NULL)return "Unknown — no quote selected";try{JSONObject c=(JSONObject)value;JSONObject expected=bind(subject,c.getInt("start"),c.getInt("end"));require(c.getString("source_hash").equals(expected.getString("source_hash"))&&c.getString("quote").equals(expected.getString("quote")),"Invalid quote binding");NotebookStore.Entry e=source(subject);return "Literal quote (manual selection; relevance not verified)\n“"+c.getString("quote")+"”\nSource: "+e.title+"\nSnapshot "+e.id+" · SHA-256 "+identity(e)+"\nUTF-16 ["+c.getInt("start")+", "+c.getInt("end")+")\n"+e.provenance;}catch(Exception e){return "Unknown — invalid, stale or missing quote/source binding";}}
 static void addDimension(JSONObject d,String name)throws Exception{JSONArray rows=d.getJSONArray("dimensions");require(rows.length()<6,"At most six dimensions");rows.put(new JSONObject().put("id",UUID.randomUUID().toString()).put("name",label(name)).put("cells",new JSONArray().put(JSONObject.NULL).put(JSONObject.NULL)));}
 static void move(JSONObject d,int index,int delta)throws Exception{JSONArray old=d.getJSONArray("dimensions");int next=index+delta;require(index>=0&&next>=0&&index<old.length()&&next<old.length(),"Cannot move dimension further");Object a=old.get(index),b=old.get(next);old.put(index,b);old.put(next,a);}
 static void swap(JSONObject d)throws Exception{JSONArray s=d.getJSONArray("subjects");Object left=s.get(0);s.put(0,s.get(1));s.put(1,left);JSONArray rows=d.getJSONArray("dimensions");for(int i=0;i<rows.length();i++){JSONArray cells=rows.getJSONObject(i).getJSONArray("cells");Object v=cells.get(0);cells.put(0,cells.get(1));cells.put(1,v);}}
 String portable(JSONObject d)throws Exception{validate(d);StringBuilder text=new StringBuilder("Manual extractive comparison — no synthesis, inference or verdict.\nLabels and notes are personal input, not source evidence.\nUnknown does not mean the subject lacks a property.\n\n");JSONArray s=d.getJSONArray("subjects"),rows=d.getJSONArray("dimensions");for(int i=0;i<rows.length();i++){JSONObject row=rows.getJSONObject(i);text.append("Dimension (personal label): ").append(row.getString("name")).append('\n');for(int j=0;j<2;j++)text.append("Subject (personal label): ").append(s.getJSONObject(j).getString("label")).append("\nSource snapshot reference: ").append(s.getJSONObject(j).getLong("record")).append(" · SHA-256 ").append(s.getJSONObject(j).getString("hash")).append('\n').append(cell(s.getJSONObject(j),row.getJSONArray("cells").get(j))).append("\n\n");}return text.append("Personal note (not source evidence):\n").append(d.getString("note")).toString();}
}
