package org.pocketlore.app;
import java.io.*;import java.nio.*;import java.nio.charset.*;import java.util.*;
/** Inert bounded HTML subset; no browser, resource loading, script execution or CSS layout. */
final class DocumentHtml {
 static final Set<String> VOID=new HashSet<>(Arrays.asList("area","base","br","col","embed","hr","img","input","link","meta","param","source","track","wbr"));
 static final Set<String> BLOCK=new HashSet<>(Arrays.asList("address","article","aside","blockquote","div","dl","dt","dd","fieldset","figcaption","figure","footer","form","h1","h2","h3","h4","h5","h6","header","hr","li","main","nav","ol","p","pre","section","table","thead","tbody","tfoot","tr","th","td","ul"));
 static final Set<String> OMIT=new HashSet<>(Arrays.asList("head","script","style","template","noscript","iframe","object","embed","svg","canvas"));
 static final Map<String,String> ENTITIES=new HashMap<>();static {String[][] pairs={{"amp","&"},{"lt","<"},{"gt",">"},{"quot","\""},{"apos","'"},{"nbsp","\u00a0"},{"copy","©"},{"reg","®"},{"ndash","–"},{"mdash","—"},{"lsquo","‘"},{"rsquo","’"},{"ldquo","“"},{"rdquo","”"},{"hellip","…"},{"eacute","é"}};for(String[] p:pairs)ENTITIES.put(p[0],p[1]);}
 static String entities(String s,StructuredDocuments.Budget budget)throws IOException{StringBuilder b=new StringBuilder();for(int i=0;i<s.length();i++){if((i&1023)==0)budget.check();char c=s.charAt(i);if(c!='&'){b.append(c);continue;}int end=-1;for(int j=i+1;j<s.length()&&j<=i+32;j++){if(s.charAt(j)==';'){end=j;break;}}if(end<0){b.append(c);continue;}String key=s.substring(i+1,end),v=ENTITIES.get(key);if(key.startsWith("#")){try{int cp=Integer.parseInt(key.substring(key.startsWith("#x")||key.startsWith("#X")?2:1),key.startsWith("#x")||key.startsWith("#X")?16:10);PersonalText.require(Character.isValidCodePoint(cp)&&!(cp>=0xd800&&cp<=0xdfff)&&cp!=0,"Invalid HTML scalar");v=new String(Character.toChars(cp));}catch(NumberFormatException e){throw new IOException("Invalid HTML numeric entity",e);}}PersonalText.require(v!=null,"Unsupported HTML entity: "+key);b.append(v);i=end;}return b.toString();}
 static String asciiLower(String s,StructuredDocuments.Budget budget)throws IOException {StringBuilder b=new StringBuilder(s.length());for(int i=0;i<s.length();i++){if((i&4095)==0)budget.check();char c=s.charAt(i);b.append(c>='A'&&c<='Z'?(char)(c+32):c);}return b.toString();}
 static boolean screen(StructuredDocuments.Node n)throws IOException {String media=n.attr("media").trim().toLowerCase(Locale.ROOT);if(media.isEmpty()||media.equals("all")||media.equals("screen"))return true;if(media.equals("print"))return false;throw new IOException("Conditional media styling unsupported");}
 static StructuredDocuments.Node parse(String text,StructuredDocuments.Budget budget)throws Exception {
  StructuredDocuments.Node root=new StructuredDocuments.Node("","root");Deque<StructuredDocuments.Node> stack=new ArrayDeque<>();stack.push(root);int i=0,count=0;String lower=asciiLower(text,budget);
  while(i<text.length()){
   budget.check();PersonalText.require(stack.size()<=StructuredDocuments.DEPTH&&count<=StructuredDocuments.NODES,"HTML structure exceeds limit");
   if(text.charAt(i)!='<'){int end=text.indexOf('<',i);if(end<0)end=text.length();stack.peek().children.add(entities(text.substring(i,end),budget));i=end;continue;}
   if(text.startsWith("<!--",i)){int end=text.indexOf("-->",i+4);PersonalText.require(end>=0,"Unclosed HTML comment");i=end+3;continue;}
   if(lower.startsWith("<!doctype",i)){int end=text.indexOf('>',i);PersonalText.require(end>=0&&text.substring(i,end+1).matches("(?is)<!doctype\\s+html\\s*>"),"External HTML doctype forbidden");i=end+1;continue;}
   if(text.startsWith("<?xml",i)){int end=text.indexOf("?>",i);PersonalText.require(i==0&&end>=0,"Invalid XML declaration");i=end+2;continue;}
   boolean closing=i+1<text.length()&&text.charAt(i+1)=='/';i+=closing?2:1;int start=i;while(i<text.length()&&(Character.isLetterOrDigit(text.charAt(i))||text.charAt(i)==':'||text.charAt(i)=='-'))i++;PersonalText.require(i>start,"Invalid HTML tag");String tag=text.substring(start,i).toLowerCase(Locale.ROOT);
   if(closing){while(i<text.length()&&Character.isWhitespace(text.charAt(i)))i++;PersonalText.require(i<text.length()&&text.charAt(i++)=='>',"Malformed HTML closing tag");PersonalText.require(stack.size()>1&&stack.peek().name.equals(tag),"Mismatched HTML closing tag");stack.pop();continue;}
   if((tag.equals("p")||BLOCK.contains(tag))&&stack.peek().name.equals("p"))stack.pop();if(tag.equals("li")&&stack.peek().name.equals("li"))stack.pop();
   StructuredDocuments.Node n=new StructuredDocuments.Node("",tag);count++;boolean self=false;
   while(true){while(i<text.length()&&Character.isWhitespace(text.charAt(i)))i++;PersonalText.require(i<text.length(),"Unclosed HTML start tag");if(text.charAt(i)=='>'){i++;break;}if(text.charAt(i)=='/'&&i+1<text.length()&&text.charAt(i+1)=='>'){i+=2;self=true;break;}start=i;while(i<text.length()&&!Character.isWhitespace(text.charAt(i))&&"=/>".indexOf(text.charAt(i))<0)i++;PersonalText.require(i>start,"Invalid HTML attribute");String key=text.substring(start,i).toLowerCase(Locale.ROOT);while(i<text.length()&&Character.isWhitespace(text.charAt(i)))i++;String value="";if(i<text.length()&&text.charAt(i)=='='){i++;while(i<text.length()&&Character.isWhitespace(text.charAt(i)))i++;PersonalText.require(i<text.length(),"Missing HTML attribute");char q=text.charAt(i);if(q=='\''||q=='"'){start=++i;int end=text.indexOf(q,i);PersonalText.require(end>=0,"Unclosed HTML attribute");value=text.substring(start,end);i=end+1;}else{start=i;while(i<text.length()&&!Character.isWhitespace(text.charAt(i))&&text.charAt(i)!='>')i++;value=text.substring(start,i);}}PersonalText.require(n.attrs.size()<64&&!n.attrs.containsKey(key),"Too many or duplicate HTML attributes");n.attrs.put(key,entities(value,budget));}
   stack.peek().children.add(n);
   if(tag.equals("script")||tag.equals("style")){String close="</"+tag;int end=lower.indexOf(close,i);PersonalText.require(end>=0,"Unclosed raw HTML element");n.children.add(text.substring(i,end));int finish=text.indexOf('>',end);PersonalText.require(finish>=0&&text.substring(end,finish+1).matches("(?is)</"+tag+"\\s*>"),"Invalid raw HTML closing tag");i=finish+1;continue;}
   if(!self&&!VOID.contains(tag))stack.push(n);
  }
  while(stack.size()>1&&Arrays.asList("p","li","body","html").contains(stack.peek().name))stack.pop();PersonalText.require(stack.size()==1,"Unclosed HTML element");return root;
 }
 static final class StyleValue {final String value;final boolean important;final int specificity;StyleValue(String v,boolean i,int s){value=v;important=i;specificity=s;}}
 static Map<String,StyleValue> declarations(String css,int specificity)throws IOException {
  PersonalText.require(css.length()<=65536,"CSS exceeds bounded static styling limit");css=comments(css);PersonalText.require(!css.contains("\\")&&!css.contains("{")&&!css.contains("}"),"Unsupported CSS syntax");Map<String,StyleValue> values=new HashMap<>();
  for(String declaration:css.split(";")){if(declaration.trim().isEmpty())continue;String[] d=declaration.split(":",2);PersonalText.require(d.length==2,"Malformed CSS declaration");String k=d[0].trim().toLowerCase(Locale.ROOT),v=d[1].trim().toLowerCase(Locale.ROOT);boolean important=v.endsWith("!important");if(important)v=v.substring(0,v.length()-10).trim();
   PersonalText.require(Arrays.asList("display","visibility","content-visibility","opacity","font-size","font-family","font-weight","font-style","line-height","text-align","text-decoration","color","background-color","margin","margin-top","margin-bottom","margin-left","margin-right","padding","padding-top","padding-bottom","padding-left","padding-right").contains(k),"Unsupported CSS layout property: "+k);
   if(k.equals("color")||k.equals("background-color"))PersonalText.require(v.matches("#[0-9a-f]{3}(?:[0-9a-f]{3})?")||Arrays.asList("black","white","red","green","blue","gray","grey","yellow","navy","silver","maroon","purple","fuchsia","lime","olive","teal","aqua","orange").contains(v),"Unsupported transparent or dynamic CSS color");
   if(k.equals("opacity")){PersonalText.require(v.matches("[+]?(?:[0-9]+(?:\\.[0-9]*)?|\\.[0-9]+)(?:e[+-]?[0-9]+)?%?"),"Unsupported opacity value");double opacity=Double.parseDouble(v.endsWith("%")?v.substring(0,v.length()-1):v);PersonalText.require(Double.isFinite(opacity)&&opacity>0,"Zero opacity is not inspectable text");}
   if(k.equals("font-size")&&!Arrays.asList("xx-small","x-small","small","medium","large","x-large","xx-large","smaller","larger").contains(v)){PersonalText.require(v.matches("[+]?(?:[0-9]+(?:\\.[0-9]*)?|\\.[0-9]+)(?:px|em|rem|pt|%)"),"Unsupported font size");double size=Double.parseDouble(v.replaceAll("(?:px|em|rem|pt|%)$",""));PersonalText.require(size>0&&Double.isFinite(size),"Zero text size unsupported");}
   if(Arrays.asList("display","visibility","content-visibility","opacity","font-size").contains(k)){
    PersonalText.require(!v.contains("var(")&&!v.contains("calc("),"Dynamic visibility CSS unsupported");
    PersonalText.require(!(k.equals("opacity")&&v.matches("0(?:\\.0+)?"))&&!(k.equals("font-size")&&v.matches("0(?:px|em|rem|pt|%)?")),"Zero opacity or text size requires layout; unsupported");
    if(k.equals("display"))PersonalText.require(Arrays.asList("none","block","inline","inline-block","flex","grid","table","table-row","table-cell","list-item","contents").contains(v),"Unsupported display value");
    if(k.equals("visibility"))PersonalText.require(Arrays.asList("visible","hidden","collapse").contains(v),"Unsupported visibility value");
    if(k.equals("content-visibility"))PersonalText.require(Arrays.asList("visible","hidden","auto").contains(v),"Unsupported content visibility");
    StyleValue old=values.get(k);if(old==null||important||!old.important)values.put(k,new StyleValue(v,important,specificity));
   }
  }return values;
 }
 static String comments(String css)throws IOException {StringBuilder b=new StringBuilder();int i=0;while(i<css.length()){int a=css.indexOf("/*",i);if(a<0){b.append(css.substring(i));break;}b.append(css.substring(i,a));int e=css.indexOf("*/",a+2);PersonalText.require(e>=0,"Unclosed CSS comment");i=e+2;}return b.toString();}
 static final class Rule {final String selector;final Map<String,StyleValue> values;Rule(String s,Map<String,StyleValue> v){selector=s;values=v;}}
 static List<Rule> styles(StructuredDocuments.Node root)throws IOException{
  List<Rule> rules=new ArrayList<>();for(StructuredDocuments.Node link:StructuredDocuments.nodes(root,"","link"))PersonalText.require(!screen(link)||!Arrays.asList(link.attr("rel").toLowerCase(Locale.ROOT).split("\\s+")).contains("stylesheet"),"External stylesheets cannot be resolved offline");
  for(StructuredDocuments.Node style:StructuredDocuments.nodes(root,"","style")){if(!screen(style))continue;StringBuilder b=new StringBuilder();for(Object c:style.children)if(c instanceof String)b.append(c);PersonalText.require(b.length()<=65536,"Stylesheet exceeds limit");String css=comments(b.toString());int i=0;while(i<css.length()){while(i<css.length()&&Character.isWhitespace(css.charAt(i)))i++;if(i==css.length())break;int open=css.indexOf('{',i),close=css.indexOf('}',open+1);PersonalText.require(open>i&&close>open,"Malformed CSS rule");String selector=css.substring(i,open).trim();for(String s:selector.split(",")){s=s.trim();PersonalText.require(s.matches("(?:[a-zA-Z][a-zA-Z0-9-]*|[.#][a-zA-Z_][a-zA-Z0-9_-]*|\\*)"),"Complex CSS selector unsupported");int specificity=s.startsWith("#")?100:s.startsWith(".")?10:s.equals("*")?0:1;PersonalText.require(rules.size()<2048,"Too many CSS rules");rules.add(new Rule(specificity<=1?s.toLowerCase(Locale.ROOT):s,declarations(css.substring(open+1,close),specificity)));}i=close+1;}}
  return rules;
 }
 static void cascade(Map<String,StyleValue> target,Map<String,StyleValue> incoming){for(Map.Entry<String,StyleValue> e:incoming.entrySet()){StyleValue old=target.get(e.getKey()),v=e.getValue();if(old==null||(v.important&&!old.important)||(v.important==old.important&&v.specificity>=old.specificity))target.put(e.getKey(),v);}}
 static Map<String,StyleValue> computed(StructuredDocuments.Node n,List<Rule> rules,StructuredDocuments.Budget budget)throws IOException {Map<String,StyleValue> out=new HashMap<>();Set<String> classes=new HashSet<>(Arrays.asList(n.attr("class").split("\\s+")));for(Rule r:rules){budget.check();String s=r.selector;if(s.equals("*")||s.equals(n.name)||s.equals("#"+n.attr("id"))||(s.startsWith(".")&&classes.contains(s.substring(1))))cascade(out,r.values);}cascade(out,declarations(n.attr("style"),1000));return out;}
 static boolean value(Map<String,StyleValue> style,String key,String value){return style.containsKey(key)&&style.get(key).value.equals(value);}
 static void visit(StructuredDocuments.Node n,List<Rule> rules,boolean inheritedHidden,StringBuilder pending,String location,StructuredDocuments.Output out,int[] ordinal)throws IOException{
  out.budget.check();if(OMIT.contains(n.name)||n.attrs.containsKey("hidden")||n.attr("aria-hidden").equalsIgnoreCase("true"))return;Map<String,StyleValue> style=computed(n,rules,out.budget);if(value(style,"display","none")||value(style,"content-visibility","hidden"))return;
  boolean hidden=style.containsKey("visibility")?!value(style,"visibility","visible"):inheritedHidden;boolean block=BLOCK.contains(n.name);if(block)flush(pending,location,out,ordinal);
  if(n.name.equals("br")&&!hidden)pending.append('\n');for(Object c:n.children){if(c instanceof String){if(!hidden)pending.append((String)c);PersonalText.require(pending.length()<=20000,"HTML paragraph exceeds limit");}else visit((StructuredDocuments.Node)c,rules,hidden,pending,location,out,ordinal);}if(block)flush(pending,location,out,ordinal);
 }
 static void flush(StringBuilder pending,String location,StructuredDocuments.Output out,int[] ordinal)throws IOException{String value=pending.toString().replaceAll("[\\t\\r\\n ]+"," ").trim();pending.setLength(0);if(!value.isEmpty())out.add(value,location+"; paragraph "+(++ordinal[0]));}
 static void localStyles(StructuredDocuments.Node node,Map<String,byte[]> files,String base,StructuredDocuments.Budget budget)throws Exception {
  for(int i=0;i<node.children.size();i++){budget.check();Object child=node.children.get(i);if(!(child instanceof StructuredDocuments.Node))continue;StructuredDocuments.Node n=(StructuredDocuments.Node)child;
   if(n.name.equals("link")&&screen(n)&&Arrays.asList(n.attr("rel").toLowerCase(Locale.ROOT).split("\\s+")).contains("stylesheet")){
    String name=StructuredDocuments.target(base,n.attr("href"));byte[] css=StructuredDocuments.required(files,name);PersonalText.require(css.length<=65536,"Linked EPUB stylesheet exceeds limit");StructuredDocuments.Node style=new StructuredDocuments.Node("","style");style.children.add(StandardCharsets.UTF_8.newDecoder().onMalformedInput(CodingErrorAction.REPORT).onUnmappableCharacter(CodingErrorAction.REPORT).decode(ByteBuffer.wrap(css)).toString());node.children.set(i,style);
   }else localStyles(n,files,base,budget);
  }
 }
 static void extract(byte[] raw,String location,StructuredDocuments.Output out)throws Exception {extract(raw,location,out,null,null);}
 static void extract(byte[] raw,String location,StructuredDocuments.Output out,Map<String,byte[]> files,String base)throws Exception {
  PersonalText.require(raw.length<=StructuredDocuments.INPUT,"HTML input exceeds limit");String text=StandardCharsets.UTF_8.newDecoder().onMalformedInput(CodingErrorAction.REPORT).onUnmappableCharacter(CodingErrorAction.REPORT).decode(ByteBuffer.wrap(raw)).toString();if(text.startsWith("\ufeff"))text=text.substring(1);StructuredDocuments.Node root=parse(text,out.budget);for(StructuredDocuments.Node meta:StructuredDocuments.nodes(root,"","meta")){String charset=meta.attr("charset");PersonalText.require(charset.isEmpty()||charset.equalsIgnoreCase("utf-8")||charset.equalsIgnoreCase("utf8"),"Only UTF-8 HTML is supported");if(meta.attr("http-equiv").equalsIgnoreCase("content-type")){String content=meta.attr("content").toLowerCase(Locale.ROOT);PersonalText.require(!content.contains("charset=")||content.matches(".*charset=\\s*[\"\']?utf-?8[\"\']?\\s*"),"Conflicting HTML encoding declaration");}}if(files!=null)localStyles(root,files,base,out.budget);List<Rule> selectors=styles(root);StringBuilder pending=new StringBuilder();int[] ordinal={0};visit(root,selectors,false,pending,location,out,ordinal);flush(pending,location,out,ordinal);out.budget.check();
 }
 private DocumentHtml(){}
}
