package org.pocketlore.app;
import android.app.*;import android.os.*;import android.content.*;import android.net.Uri;import android.provider.OpenableColumns;import android.widget.*;import java.io.*;import java.util.concurrent.*;
/** Collection import/export entry point; shared search/source reader and Saved UX stay unchanged. */
public final class PersonalDocumentsActivity extends Activity {
 private final ExecutorService worker=Executors.newSingleThreadExecutor();private volatile boolean cancel,closed;private volatile Thread thread;private boolean busy;private TextView status;private EditText owner,date;private Button pick,export;private String exportHash;
 @Override public void onCreate(Bundle b){super.onCreate(b);LinearLayout box=ReaderUi.column(this);ReaderUi.screen(this,box,"Library");
  TextView title=ReaderUi.text(this,"Personal documents",24);ReaderUi.heading(title);box.addView(title);TextView info=ReaderUi.text(this,"",16);info.setText("Import TXT, MD, quoted CSV, JSON, text PDF (Android 15+), DOCX, PPTX, ODT, ODP, EPUB or HTML. Up to 4 MiB input, 500,000 extracted characters and 100 PDF pages. Scanned/password PDFs, encrypted documents and active content are not supported. Office layout is linearized; complex HTML styling may be refused. Personal ownership is not public redistribution permission. Search and source inspection use your existing active collections.");box.addView(info);
  owner=new EditText(this);ReaderUi.label(this,box,owner,"Owner or author (your statement)");owner.setTextColor(ReaderUi.CREAM);box.addView(owner);date=new EditText(this);ReaderUi.label(this,box,date,"Source date, or Unknown");date.setTextColor(ReaderUi.CREAM);date.setText("Unknown");box.addView(date);
  pick=new Button(this);pick.setText("Choose personal document");ReaderUi.styleButton(this,pick,false);box.addView(pick);pick.setOnClickListener(v->{if(!busy){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).putExtra(Intent.EXTRA_LOCAL_ONLY,true).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,10);}});
  export=new Button(this);export.setText("Export a portable collection");ReaderUi.styleButton(this,export,false);box.addView(export);export.setOnClickListener(v->chooseExport());Button stop=new Button(this);stop.setText("Cancel operation");ReaderUi.styleButton(this,stop,false);box.addView(stop);stop.setOnClickListener(v->{cancel=true;if(thread!=null)thread.interrupt();});
  Button done=new Button(this);done.setText("Return to library and search");ReaderUi.styleButton(this,done,false);box.addView(done);done.setOnClickListener(v->{if(!busy){setResult(RESULT_OK);finish();}});status=ReaderUi.text(this,"",16);ReaderUi.status(status);status.setTextIsSelectable(true);box.addView(status);if(b!=null){owner.setText(b.getString("owner",""));date.setText(b.getString("date","Unknown"));exportHash=b.getString("export_hash");status.setText("Any interrupted operation was cancelled. Retained collections remain available.");}
 }
 void execute(Work action){if(busy)return;busy=true;cancel=false;pick.setEnabled(false);export.setEnabled(false);worker.execute(()->{thread=Thread.currentThread();try{action.run();}catch(Exception|OutOfMemoryError e){message("Operation stopped; retained collections are unchanged. "+e.getMessage());}finally{thread=null;Thread.interrupted();runOnUiThread(()->{if(!closed){busy=false;pick.setEnabled(true);export.setEnabled(true);}});}});}
 interface Work{void run()throws Exception;}
 void message(String text){runOnUiThread(()->{if(!closed)status.setText(text);});}
 void chooseExport(){if(busy)return;execute(()->{PackLibrary.Snapshot s=new PackLibrary(getFilesDir()).load();String[] labels=new String[s.entries.size()];for(int i=0;i<labels.length;i++)labels[i]=s.entries.get(i).id;runOnUiThread(()->{if(closed)return;new AlertDialog.Builder(this).setTitle("Export includes original private bytes and source metadata").setItems(labels,(d,n)->{exportHash=s.entries.get(n).hash;Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT).putExtra(Intent.EXTRA_LOCAL_ONLY,true).addCategory(Intent.CATEGORY_OPENABLE).setType("application/zip").putExtra(Intent.EXTRA_TITLE,s.entries.get(n).id+".plpack");startActivityForResult(i,11);}).setNegativeButton("Cancel",null).show();});});}
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;Uri uri=data.getData();
  if(request==10){String author=owner.getText().toString(),sourceDate=date.getText().toString();execute(()->{StructuredDocuments.Budget operation=new StructuredDocuments.Budget(()->cancel||closed);operation.check();String name=null;long size=-1;try(android.database.Cursor c=getContentResolver().query(uri,new String[]{OpenableColumns.DISPLAY_NAME,OpenableColumns.SIZE},null,null,null)){if(c!=null&&c.moveToFirst()){name=c.getString(0);if(!c.isNull(1))size=c.getLong(1);}}if(name==null)throw new IOException("Provider omitted filename");if(size>PersonalDocuments.MAX_INPUT)throw new IOException("Input exceeds 4 MiB");ResourceStorage.requireSpace(16L*1024*1024,getFilesDir().getUsableSpace());message("Extracting local document…");byte[] pack;try(InputStream in=DocumentInput.open(getContentResolver(),uri,operation)){pack=PersonalDocuments.convert(in,name,getContentResolver().getType(uri),author,sourceDate,uri.toString(),getCacheDir(),operation);}PackLibrary.Snapshot s=new PackLibrary(getFilesDir()).install(new ByteArrayInputStream(pack),operation,pack.length);message("Imported. "+s.description()+". Return to search or change active collections.");});}
  if(request==11&&exportHash!=null){String hash=exportHash;execute(()->{try(OutputStream out=DocumentOutput.open(getContentResolver(),uri,()->cancel||closed)){if(out==null)throw new IOException("Cannot open export destination");new PackLibrary(getFilesDir()).exportCollection(hash,out,()->cancel||closed);}catch(Exception e){boolean removed=false;try{removed=android.provider.DocumentsContract.deleteDocument(getContentResolver(),uri);}catch(Exception ignored){}throw new IOException(removed?"Export cancelled or failed; new destination removed.":"Export cancelled or failed; a partial destination may remain. Delete it before retrying.",e);}message("Portable collection exported. It contains private source bytes and metadata.");});}
 }
 @Override protected void onSaveInstanceState(Bundle b){super.onSaveInstanceState(b);b.putString("owner",owner.getText().toString());b.putString("date",date.getText().toString());b.putString("export_hash",exportHash);}
 @Override protected void onDestroy(){closed=true;cancel=true;if(thread!=null)thread.interrupt();worker.shutdownNow();super.onDestroy();}
}
