package org.pocketlore.app;
import java.io.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.util.*;import java.util.function.BooleanSupplier;import java.util.zip.*;import org.json.*;
/** Portable personal archives reuse PackLibrary transactions; no public rights are inferred. */
public final class PersonalDocuments {
 public static final int MAX_INPUT=4*1024*1024;
 static final String RIGHTS="Personal import; ownership supplied by importer; redistribution rights not verified";
 static byte[] read(InputStream in,int limit,BooleanSupplier cancel)throws IOException{ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;while(true){PersonalText.check(cancel);n=in.read(b);if(n==-1)break;PersonalText.check(cancel);if(out.size()+n>limit)throw new IOException("Document exceeds size limit");out.write(b,0,n);}PersonalText.check(cancel);return out.toByteArray();}
 static String meta(String value)throws IOException{PersonalText.require(value!=null&&!value.trim().isEmpty()&&value.length()<=2048&&!value.matches("(?s).*[\\p{Cntrl}].*"),"Invalid document metadata");return value;}
 public static byte[] convert(InputStream input,String name,String owner,String date,String location,File cache,BooleanSupplier cancel)throws Exception {
  meta(name);meta(owner);meta(date);meta(location);byte[] raw=read(input,MAX_INPUT,cancel);PersonalText.require(raw.length>0,"Empty document");String ext=name.substring(name.lastIndexOf('.')+1).toLowerCase(Locale.ROOT);String text;List<PersonalText.Span> spans;
  if(ext.equals("pdf")){PdfText.Result result=PdfText.extract(raw,cache,cancel);text=result.text;spans=result.spans;}
  else{text=PersonalText.decode(raw);switch(ext){case "txt":case "md":spans=PersonalText.plain(text,cancel);break;case "csv":spans=PersonalText.csv(text,cancel);break;case "json":spans=PersonalText.json(text,cancel);break;default:throw new IOException("Choose UTF-8 TXT, MD, CSV, JSON or a text PDF");}}
  PersonalText.validate(text);PersonalText.require(!spans.isEmpty(),"No searchable text extracted");JSONArray entries=new JSONArray();
  for(PersonalText.Span s:spans){PersonalText.check(cancel);entries.put(new JSONObject().put("start",s.start).put("end",s.end).put("location",s.location).put("sha256",KnowledgePack.hash(text.substring(s.start,s.end).getBytes(StandardCharsets.UTF_8))));}
  JSONObject m=new JSONObject().put("schema","personal-document-v1").put("name",name).put("owner",owner).put("source_date",date).put("imported_at",java.time.Instant.now().toString()).put("source_location",location).put("rights",RIGHTS).put("format",ext).put("raw_sha256",KnowledgePack.hash(raw)).put("text_sha256",KnowledgePack.hash(text.getBytes(StandardCharsets.UTF_8))).put("offset_convention","UTF-16 offsets in exact extracted text.txt, not PDF byte offsets").put("passages",entries);
  ByteArrayOutputStream buffer=new ByteArrayOutputStream();try(ZipOutputStream zip=new ZipOutputStream(buffer)){put(zip,"personal.json",m.toString().getBytes(StandardCharsets.UTF_8));put(zip,"original.bin",raw);put(zip,"text.txt",text.getBytes(StandardCharsets.UTF_8));}PersonalText.check(cancel);byte[] archive=buffer.toByteArray();PersonalText.require(archive.length<=KnowledgePack.LIMIT,"Personal archive exceeds limit");return archive;
 }
 static void put(ZipOutputStream zip,String name,byte[] b)throws IOException{ZipEntry e=new ZipEntry(name);e.setTime(0);zip.putNextEntry(e);zip.write(b);zip.closeEntry();}
 static KnowledgePack decode(byte[] archive,boolean index)throws Exception {
  Map<String,byte[]> files=new HashMap<>();try(ZipInputStream zip=new ZipInputStream(new ByteArrayInputStream(archive))){ZipEntry e=zip.getNextEntry();if(e==null||!e.getName().equals("personal.json"))return null;
   do{String n=e.getName();PersonalText.require(Arrays.asList("personal.json","original.bin","text.txt").contains(n)&&!files.containsKey(n)&&!e.isDirectory(),"Invalid personal archive entry");files.put(n,read(zip,n.equals("personal.json")?2*1024*1024:MAX_INPUT,()->false));zip.closeEntry();}while((e=zip.getNextEntry())!=null);}
  PersonalText.require(files.size()==3,"Incomplete personal archive");validateDirectory(archive,files);
  JSONObject m=new JSONObject(new String(files.get("personal.json"),StandardCharsets.UTF_8));PersonalText.require(m.getString("schema").equals("personal-document-v1")&&m.getString("rights").equals(RIGHTS),"Unsupported personal schema or rights claim");
  String name=meta(m.getString("name")),owner=meta(m.getString("owner")),date=meta(m.getString("source_date")),location=meta(m.getString("source_location"));meta(m.getString("imported_at"));String format=meta(m.getString("format"));
  PersonalText.require(Arrays.asList("txt","md","csv","json","pdf").contains(format),"Unsupported stored document format");
  PersonalText.require(KnowledgePack.hash(files.get("original.bin")).equals(m.getString("raw_sha256"))&&KnowledgePack.hash(files.get("text.txt")).equals(m.getString("text_sha256")),"Personal document integrity failure");
  String text=PersonalText.decode(files.get("text.txt"));if(!format.equals("pdf"))PersonalText.require(text.equals(PersonalText.decode(files.get("original.bin"))),"Original and extracted text differ");JSONArray segments=m.getJSONArray("passages");PersonalText.require(segments.length()>0&&segments.length()<=PersonalText.MAX_SEGMENTS,"Invalid passage count");
  List<String[]> rows=new ArrayList<>();Map<String,String> provenance=new HashMap<>(),keys=new HashMap<>();String rawHash=m.getString("raw_sha256"),textHash=m.getString("text_sha256");int previous=-1;
  for(int i=0;i<segments.length();i++){JSONObject s=segments.getJSONObject(i);int a=s.getInt("start"),b=s.getInt("end");PersonalText.require(a>=0&&a>=previous&&b>a&&b<=text.length()&&b-a<=20000,"Invalid personal citation offsets");PersonalText.require(!(a>0&&Character.isLowSurrogate(text.charAt(a)))&&!(b<text.length()&&Character.isLowSurrogate(text.charAt(b))),"Split citation Unicode character");previous=b;String passage=text.substring(a,b);PersonalText.require(KnowledgePack.hash(passage.getBytes(StandardCharsets.UTF_8)).equals(s.getString("sha256")),"Personal passage hash mismatch");String citation="d"+rawHash.substring(0,16)+"-"+a+"-"+b;String where=meta(s.getString("location"));String title=name+" · "+where;
   rows.add(new String[]{citation,title,"personal://"+rawHash,date,RIGHTS,passage});keys.put(citation,rawHash+"\n"+textHash);provenance.put(citation,"Personal source: "+name+"\nOwnership (importer supplied): "+owner+"\nSource location (may not exist on another device): "+location+"\nImported: "+m.getString("imported_at")+"\nOriginal SHA-256: "+rawHash+"\nExtracted SHA-256: "+textHash+"\n"+where+"\nExact extracted UTF-16 offsets: ["+a+", "+b+")\n"+RIGHTS);}
  List<ResearchEngine.Passage> indexed=new ArrayList<>();if(index)for(String[] row:rows)indexed.add(new ResearchEngine.Passage(row,provenance.get(row[0])));
  return new KnowledgePack(index?new ResearchEngine(indexed):null,"personal-"+rawHash.substring(0,24),"Personal collection; export contains original private bytes and location metadata. Text extraction does not establish answer support.",KnowledgePack.hash(archive),rows,provenance,keys,archive.length,files.values().stream().mapToLong(b->b.length).sum(),files.get("personal.json").length,1);
 }
 static void validateDirectory(byte[] archive,Map<String,byte[]> files)throws Exception {
  File temp=File.createTempFile("personal-verify-",".zip");try{Files.write(temp.toPath(),archive);try(ZipFile zip=new ZipFile(temp)){PersonalText.require(zip.size()==3,"Invalid personal ZIP directory");Set<String> seen=new HashSet<>();Enumeration<? extends ZipEntry> en=zip.entries();while(en.hasMoreElements()){ZipEntry e=en.nextElement();PersonalText.require(files.containsKey(e.getName())&&seen.add(e.getName()),"Personal ZIP directory mismatch");byte[] b=files.get(e.getName());CRC32 crc=new CRC32();crc.update(b);PersonalText.require(e.getSize()==b.length&&e.getCrc()==crc.getValue(),"Personal ZIP directory integrity");}}}finally{temp.delete();}
 }
 private PersonalDocuments(){}
}
