package org.pocketlore.app;
import android.app.*;import android.os.Bundle;import android.content.Intent;import android.widget.*;import java.io.*;import java.util.*;
/** Offline bulk browsing remains separate from generation until source rights/support are reviewed. */
public final class ScaleActivity extends Activity {
 NearbyTravel nearby; String sectionName; Button cancelButton; LinearLayout layout,results;TextView status;EditText query,city,category,radius;volatile boolean cancelled;volatile InputStream input;Thread worker;ScaleLibrary library;AlertDialog dialog;
 interface Work {void run()throws Exception;}
 void run(Work work){if(worker!=null&&worker.isAlive()){status.setText("An operation is running. Cancel it first.");return;}cancelled=false;if(cancelButton!=null)cancelButton.setVisibility(0);((android.view.inputmethod.InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(layout.getWindowToken(),0);status.setText("Working offline…");worker=new Thread(()->{try{work.run();}catch(Exception e){runOnUiThread(()->status.setText(cancelled?"Operation cancelled. Installed sources are unchanged.":"Could not complete: "+e.getMessage()));}finally{runOnUiThread(()->{if(cancelButton!=null)cancelButton.setVisibility(8);});}},"bulk-library");worker.start();}
 Button button(String label,Runnable action){return ReaderUi.button(this,layout,label,action);}
 TextView text(String s){TextView t=ReaderUi.text(this,s,18);t.setTextIsSelectable(true);return t;}
 @Override public void onCreate(Bundle b){super.onCreate(b);sectionName=getIntent().getStringExtra("section");if(sectionName==null)sectionName="Knowledge";layout=ReaderUi.column(this);ReaderUi.screen(this,layout,sectionName.equals("Places")?"Explore":"Library");ReaderUi.title(this,layout,sectionName.equals("Places")?"Explore":"Library",sectionName.equals("Places")?"Search installed place records.":"Read the sources. Keep what matters.");status=text("Offline • Installed collections");ReaderUi.status(status);layout.addView(status);try{library=new ScaleLibrary(getFilesDir());}catch(Exception e){status.setText("Library unavailable: "+e.getMessage());return;}
 if(!sectionName.equals("Places"))button("Personal documents and collection export",()->startActivityForResult(new Intent(this,PersonalDocumentsActivity.class),330));
 LinearLayout page=layout;LinearLayout tools=ReaderUi.column(this);Button manage=button("Collection storage & licenses",()->tools.setVisibility(tools.getVisibility()==android.view.View.GONE?android.view.View.VISIBLE:android.view.View.GONE));page.addView(tools);tools.setVisibility(android.view.View.GONE);layout=tools;
 button("Import bulk collection",()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");i.putExtra(Intent.EXTRA_LOCAL_ONLY,true);startActivityForResult(i,300);});
 button("Active bulk collections",this::collections);button("Collection licenses",()->run(()->{List<ScaleLibrary.Entry> es=library.entries();String[] names=new String[es.size()];for(int i=0;i<es.size();i++)names[i]=es.get(i).manifest.optString("label");runOnUiThread(()->new AlertDialog.Builder(this).setTitle("Collection licenses").setItems(names,(d,i)->run(()->{StringBuilder notices=new StringBuilder();org.json.JSONArray fs=es.get(i).manifest.getJSONArray("files");for(int n=0;n<fs.length();n++){String path=fs.getJSONObject(n).getString("path");if(path.endsWith(".txt")){File f=ScaleLibrary.resolve(es.get(i).directory,path);ScaleLibrary.check(f.length()<=1024*1024,"Notice display bound");notices.append(path).append("\n").append(new String(java.nio.file.Files.readAllBytes(f.toPath()),java.nio.charset.StandardCharsets.UTF_8)).append("\n\n");}}show(names[i],notices.toString());})).setNegativeButton("Close",null).show());}));
 layout=page;LinearLayout management=layout;
 LinearLayout knowledge=ReaderUi.column(this),places=ReaderUi.column(this);knowledge.setPadding(0,0,0,0);places.setPadding(0,0,0,0);
 management.addView(knowledge);management.addView(places);knowledge.setVisibility(sectionName.equals("Places")?8:0);places.setVisibility(sectionName.equals("Places")?0:8);layout=knowledge;
 query=new EditText(this);ReaderUi.label(this,layout,query,"Knowledge topic");query.setHint("Reference topic");layout.addView(query);button("Search reference",()->{String q=query.getText().toString();run(()->{List<ResearchEngine.Passage> starter=starterSources(q);List<ScaleWiki.Hit> hits=new ArrayList<>();for(ScaleLibrary.Entry e:library.entries())if(e.active&&e.kind().equals("wiki"))hits.addAll(ScaleWiki.search(e,q,()->cancelled));runOnUiThread(()->{results.removeAllViews();status.setText(hits.isEmpty()&&starter.isEmpty()?"No matching articles in active installed collections. Import or select a Knowledge collection to search more sources.":(hits.size()+starter.size())+" source matches · Open to read");for(ResearchEngine.Passage p:starter)sourceRow(p);for(ScaleWiki.Hit h:hits){Button item=new Button(this);ReaderUi.styleButton(this,item,false);item.setText(h.title+" · "+h.tier);results.addView(item);item.setOnClickListener(v->run(()->{ScaleWiki.Read r=ScaleWiki.read(h,getCacheDir(),()->cancelled);show(h.title,ScaleWiki.detail(h,r));}));}});});});
 layout=places;city=new EditText(this);ReaderUi.label(this,layout,city,"City name");city.setHint("City name (choose an exact location)");layout.addView(city);category=new EditText(this);ReaderUi.label(this,layout,category,"Source category (optional)");category.setHint("Optional source category, e.g. museum");layout.addView(category);radius=new EditText(this);ReaderUi.label(this,layout,radius,"Straight-line radius (km)");radius.setHint("Straight-line radius in km (up to 100)");radius.setText("1");radius.setInputType(8194);layout.addView(radius);button("Find city",()->{String name=city.getText().toString(),cat=category.getText().toString().trim(),radiusText=radius.getText().toString();run(()->{double km=Double.parseDouble(radiusText);List<ScaleLibrary.Entry> es=library.entries();runOnUiThread(()->{results.removeAllViews();status.setText("No matching cities in active installed Places collections.");});for(ScaleLibrary.Entry e:es)if(e.active&&e.kind().equals("places")){List<ScalePlaces.City> cities=ScalePlaces.cities(e,name,()->cancelled);runOnUiThread(()->{results.removeAllViews();status.setText(cities.isEmpty()?"No matching city in the installed collection.":"Choose a city; results use your radius, not municipal boundaries.");for(ScalePlaces.City c:cities){Button item=new Button(this);ReaderUi.styleButton(this,item,false);item.setText(c.name+", "+c.country+" · "+c.lat+", "+c.lon);results.addView(item);item.setOnClickListener(v->{try{nearby.search(c.lat,c.lon,c);}catch(Exception error){status.setText("Enter a radius above zero and at most 100 km.");}});}});break;}});});nearby=new NearbyTravel(this,places);layout=management; cancelButton=button("Cancel operation",()->{cancelled=true;if(nearby!=null)nearby.stop();Thread t=worker;if(t!=null)t.interrupt();InputStream in=input;if(in!=null)new Thread(()->{try{in.close();}catch(Exception ignored){}}).start();});

 results=new LinearLayout(this);results.setOrientation(1);layout.addView(results);if(!sectionName.equals("Places"))run(()->{List<ResearchEngine.Passage> sources=starterSources("");runOnUiThread(()->{for(ResearchEngine.Passage p:sources)sourceRow(p);status.setText("Bundled sources · Search all active collections above");});});cancelButton.setVisibility(8);page.removeView(manage);page.removeView(tools);page.addView(manage);page.addView(tools);if(sectionName.equals("Places")){page.addView(text("Hours and diet suitability are unknown. Routing is unavailable. Distances are straight-line, not travel routes."));button("Regional travel & tools",()->startActivity(new Intent(this,TravelActivity.class)));}
 if(b!=null){query.setText(b.getString("query",""));city.setText(b.getString("city",""));category.setText(b.getString("category",""));radius.setText(b.getString("radius","1"));}

 }
 List<ResearchEngine.Passage> starterSources(String query)throws Exception{
  List<ResearchEngine.Passage> found=new ArrayList<>();try(BufferedReader r=new BufferedReader(new InputStreamReader(getAssets().open("water-science.tsv"),java.nio.charset.StandardCharsets.UTF_8))){String line;while((line=r.readLine())!=null){if(line.startsWith("#")||line.startsWith("id\t"))continue;String[] row=line.split("\t",-1);if(row.length!=6)continue;ResearchEngine.Passage p=new ResearchEngine.Passage(row);if(query.trim().isEmpty()||(p.title+" "+p.text).toLowerCase(Locale.ROOT).contains(query.trim().toLowerCase(Locale.ROOT)))found.add(p);}}return found;
 }
 void sourceRow(ResearchEngine.Passage p){ReaderUi.entry(this,results,p.title,"USGS · Bundled source",()->ReaderUi.openSource(this,p.title,p.text+"\n\nSource document: "+p.title+"\n"+p.url+"\nSource date / retrieval: "+(p.sourceDate.isEmpty()?"Unknown":p.sourceDate)+"\nRights: "+p.license+"\nCitation: ["+p.id+"]","Bundled water-science passage. Verbatim USGS paragraph with whitespace normalized; limited coverage, not a complete publication."));}
 void show(String title,String detail){runOnUiThread(()->{if(isDestroyed()||cancelled)return;ReaderUi.openSource(this,title,detail,"Installed bulk source snapshot. Full/lead tier, source date, license and edition are supplied in the source detail where available; missing fields remain unknown. Bulk browsing does not grant generation rights.");status.setText("Source inspected offline.");});}
 void collections(){run(()->{List<ScaleLibrary.Entry> es=library.entries();String[] names=new String[es.size()];boolean[] checked=new boolean[es.size()];for(int i=0;i<es.size();i++){names[i]=es.get(i).manifest.optString("label")+" · "+es.get(i).bytes()+" bytes";checked[i]=es.get(i).active;}runOnUiThread(()->dialog=new AlertDialog.Builder(this).setTitle("Active bulk collections").setMultiChoiceItems(names,checked,(d,i,v)->checked[i]=v).setPositiveButton("Apply",(d,w)->run(()->{Set<String> ids=new HashSet<>();for(int i=0;i<es.size();i++)if(checked[i])ids.add(es.get(i).id);library.select(ids);runOnUiThread(()->status.setText(ids.size()+" active collections saved."));})).setNegativeButton("Cancel",null).show());});}
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==330){startActivity(new Intent(this,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP).putExtra("reload_library",true));finish();return;}if(request==300&&result==RESULT_OK&&data!=null)run(()->{try(InputStream in=getContentResolver().openInputStream(data.getData())){input=in;ScaleLibrary.Entry e=library.install(in,()->cancelled);runOnUiThread(()->status.setText("Installed "+e.manifest.optString("label")+"; "+e.bytes()+" bytes."+(library.lastAdmissionPeak>ScaleLibrary.TARGET?" Update is above the 45 GB target but below the 50 GB hard limit.":"")));}finally{input=null;}});}
 @Override public void onSaveInstanceState(Bundle b){super.onSaveInstanceState(b);if(query!=null){b.putString("section",sectionName);b.putString("query",query.getText().toString());b.putString("city",city.getText().toString());b.putString("category",category.getText().toString());b.putString("radius",radius.getText().toString());}}
 @Override public void onLowMemory(){ScaleWiki.clearPreviewCache();super.onLowMemory();}
 @Override public void onTrimMemory(int level){super.onTrimMemory(level);if(level>=android.content.ComponentCallbacks2.TRIM_MEMORY_RUNNING_LOW)ScaleWiki.clearPreviewCache();}
 @Override protected void onStop(){if(nearby!=null)nearby.stop();super.onStop();}
 @Override public void onRequestPermissionsResult(int request,String[] permissions,int[] results){super.onRequestPermissionsResult(request,permissions,results);if(request==360){if(results.length>0&&results[0]==android.content.pm.PackageManager.PERMISSION_GRANTED)nearby.gps();else status.setText("Location permission denied. Enter coordinates or choose a city manually.");}}
 @Override public void onDestroy(){cancelled=true;if(worker!=null)worker.interrupt();InputStream in=input;if(in!=null)new Thread(()->{try{in.close();}catch(Exception ignored){}}).start();super.onDestroy();}
}
