package org.pocketlore.app;
import android.database.Cursor;import android.database.sqlite.SQLiteDatabase;import java.util.*;import java.util.function.BooleanSupplier;import java.text.Normalizer;import org.pocketlore.places.CompactPlaces;
/** City lookup and deterministic shard merge; city coordinates are not municipal boundaries. */
final class ScalePlaces {
 static final class City {String id,name,country,date,raw;double lat,lon;}
 static final class Hit {ScaleLibrary.Entry edition;String shard;CompactPlaces.Place place;String identity(){return edition.id+":"+shard+":"+place.id+":"+place.sourceOrdinal;}}
 static List<City> cities(ScaleLibrary.Entry e,String name,BooleanSupplier cancel)throws Exception{ScaleLibrary.cancelled(cancel);ScaleLibrary.check(name.length()<=200,"City query bound");String key=Normalizer.normalize(name,Normalizer.Form.NFKC).toLowerCase(Locale.ROOT).trim().replaceAll("\\s+"," ");List<City> out=new ArrayList<>();try(SQLiteDatabase db=SQLiteDatabase.openDatabase(ScaleLibrary.resolve(e.directory,e.manifest.getString("cities")).getPath(),null,SQLiteDatabase.OPEN_READONLY);Cursor c=db.rawQuery("SELECT c.id,c.name,c.country,c.lat,c.lon,c.modified,c.raw FROM city c JOIN alias a ON a.city_id=c.id WHERE a.name_key=? ORDER BY c.population DESC,c.id LIMIT 20",new String[]{key})){while(c.moveToNext()){ScaleLibrary.cancelled(cancel);City city=new City();city.id=c.getString(0);city.name=c.getString(1);city.country=c.getString(2);city.lat=c.getDouble(3);city.lon=c.getDouble(4);city.date=c.getString(5);city.raw=c.getString(6);out.add(city);}}return out;}
 static List<Hit> nearby(ScaleLibrary.Entry e,double lat,double lon,double radius,String category,BooleanSupplier cancel)throws Exception{List<Hit> out=new ArrayList<>();for(int i=0;i<e.manifest.getJSONArray("shards").length();i++){ScaleLibrary.cancelled(cancel);String shard=e.manifest.getJSONArray("shards").getString(i);try(CompactPlaces reader=new CompactPlaces(ScaleLibrary.resolve(e.directory,shard).getPath(),cancel)){for(CompactPlaces.Place p:reader.nearby(lat,lon,radius,category,30)){Hit h=new Hit();h.edition=e;h.shard=shard;h.place=p;out.add(h);}}}out.sort(Comparator.comparingDouble((Hit h)->h.place.distanceKm).thenComparing(Hit::identity));return out.subList(0,Math.min(30,out.size()));}
 static String detail(Hit h,BooleanSupplier cancel)throws Exception{try(CompactPlaces r=new CompactPlaces(ScaleLibrary.resolve(h.edition.directory,h.shard).getPath(),cancel)){return h.place.name+"\n"+h.place.category+"\nStraight-line distance: "+String.format(Locale.ROOT,"%.3f km",h.place.distanceKm)+"\nCurrent hours and diet suitability: unknown. Routing unavailable.\nSnapshot status is not live availability.\nEdition/source identity: "+h.identity()+"\nSource release: "+r.metadataJson("release")+"\nSource provenance and attribution (unaltered retained fields):\n"+r.sourceJson(h.place)+"\nGeoNames city lookup: CC BY 4.0; city proximity is not municipal containment.\nSource-specific terms are retained in collection notices; no generated answer clearance.";}}
}
