package org.pocketlore.app;
import android.app.*;import android.os.Bundle;import android.content.Intent;import android.widget.*;import java.io.*;import java.util.*;
/** Offline bulk browsing remains separate from generation until source rights/support are reviewed. */
public final class ScaleActivity extends Activity {
 LinearLayout layout,results;TextView status;EditText query,city,category,radius;volatile boolean cancelled;volatile InputStream input;Thread worker;ScaleLibrary library;AlertDialog dialog;
 interface Work {void run()throws Exception;}
 void run(Work work){if(worker!=null&&worker.isAlive()){status.setText("An operation is running. Cancel it first.");return;}cancelled=false;status.setText("Working offline…");worker=new Thread(()->{try{work.run();}catch(Exception e){runOnUiThread(()->status.setText(e.getMessage()));}},"bulk-library");worker.start();}
 void button(String label,Runnable action){Button b=new Button(this);b.setText(label);layout.addView(b);b.setOnClickListener(v->action.run());}
 TextView text(String s){TextView t=new TextView(this);t.setText(s);t.setTextIsSelectable(true);t.setPadding(12,12,12,12);return t;}
 @Override public void onCreate(Bundle b){super.onCreate(b);ScrollView scroll=new ScrollView(this);layout=new LinearLayout(this);layout.setOrientation(1);scroll.addView(layout);setContentView(scroll);layout.addView(text("Reference and world places\nPartial offline collections. Browse source records; bulk sources are not cleared for generated answers."));status=text("");layout.addView(status);try{library=new ScaleLibrary(getFilesDir());}catch(Exception e){status.setText(e.toString());return;}
 button("Import bulk collection",()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");i.putExtra(Intent.EXTRA_LOCAL_ONLY,true);startActivityForResult(i,300);});
 button("Cancel operation",()->{cancelled=true;Thread t=worker;if(t!=null)t.interrupt();InputStream in=input;if(in!=null)new Thread(()->{try{in.close();}catch(Exception ignored){}}).start();});
 button("Active bulk collections",this::collections);button("Collection licenses",()->run(()->{List<ScaleLibrary.Entry> es=library.entries();String[] names=new String[es.size()];for(int i=0;i<es.size();i++)names[i]=es.get(i).manifest.optString("label");runOnUiThread(()->new AlertDialog.Builder(this).setTitle("Collection licenses").setItems(names,(d,i)->run(()->{StringBuilder notices=new StringBuilder();org.json.JSONArray fs=es.get(i).manifest.getJSONArray("files");for(int n=0;n<fs.length();n++){String path=fs.getJSONObject(n).getString("path");if(path.endsWith(".txt")){File f=ScaleLibrary.resolve(es.get(i).directory,path);ScaleLibrary.check(f.length()<=1024*1024,"Notice display bound");notices.append(path).append("\n").append(new String(java.nio.file.Files.readAllBytes(f.toPath()),java.nio.charset.StandardCharsets.UTF_8)).append("\n\n");}}show(names[i],notices.toString());})).setNegativeButton("Close",null).show());}));
 query=new EditText(this);query.setHint("Reference topic");layout.addView(query);button("Search reference",()->{String q=query.getText().toString();run(()->{List<ScaleWiki.Hit> hits=new ArrayList<>();for(ScaleLibrary.Entry e:library.entries())if(e.active&&e.kind().equals("wiki"))hits.addAll(ScaleWiki.search(e,q,()->cancelled));runOnUiThread(()->{results.removeAllViews();status.setText(hits.size()+" article candidates; relevance is not answer support.");for(ScaleWiki.Hit h:hits){Button item=new Button(this);item.setText(h.title+" · "+h.tier);results.addView(item);item.setOnClickListener(v->run(()->{ScaleWiki.Read r=ScaleWiki.read(h,getCacheDir(),()->cancelled);ScaleAnswerAdapter.Ledger reviews=BulkSourceReviews.load(getAssets().open("bulk-source-reviews.json"));show(h.title,ScaleWiki.detail(h,r)+"\n\n"+ScaleWiki.answerReview(h,r,reviews));}));}});});});
 city=new EditText(this);city.setHint("City name (choose an exact location)");layout.addView(city);category=new EditText(this);category.setHint("Optional source category, e.g. museum");layout.addView(category);radius=new EditText(this);radius.setHint("Straight-line radius in km (up to 100)");radius.setText("1");radius.setInputType(8194);layout.addView(radius);button("Find city",()->{String name=city.getText().toString(),cat=category.getText().toString().trim(),radiusText=radius.getText().toString();run(()->{double km=Double.parseDouble(radiusText);List<ScaleLibrary.Entry> es=library.entries();for(ScaleLibrary.Entry e:es)if(e.active&&e.kind().equals("places")){List<ScalePlaces.City> cities=ScalePlaces.cities(e,name,()->cancelled);runOnUiThread(()->{results.removeAllViews();status.setText("Choose a city; results use your radius, not municipal boundaries.");for(ScalePlaces.City c:cities){Button item=new Button(this);item.setText(c.name+", "+c.country+" · "+c.lat+", "+c.lon);results.addView(item);item.setOnClickListener(v->run(()->{List<ScalePlaces.Hit> hits=new ArrayList<>();for(ScaleLibrary.Entry active:library.entries())if(active.active&&active.kind().equals("places"))hits.addAll(ScalePlaces.nearby(active,c.lat,c.lon,km,cat,()->cancelled));hits.sort(java.util.Comparator.comparingDouble(h->h.place.distanceKm));runOnUiThread(()->{results.removeAllViews();status.setText(hits.size()+" nearby candidates. Current hours/diet unknown; routing unavailable.");for(ScalePlaces.Hit h:hits){Button p=new Button(this);p.setText(h.place.name+" · "+h.place.category);results.addView(p);p.setOnClickListener(w->run(()->show(h.place.name,ScalePlaces.detail(h,()->cancelled))));}});}));}});break;}});});results=new LinearLayout(this);results.setOrientation(1);layout.addView(results);}
 void show(String title,String detail){runOnUiThread(()->{ScrollView s=new ScrollView(this);s.addView(text(detail));dialog=new AlertDialog.Builder(this).setTitle(title).setView(s).setPositiveButton("Close",null).show();status.setText("Source inspected offline.");});}
 void collections(){run(()->{List<ScaleLibrary.Entry> es=library.entries();String[] names=new String[es.size()];boolean[] checked=new boolean[es.size()];for(int i=0;i<es.size();i++){names[i]=es.get(i).manifest.optString("label")+" · "+es.get(i).bytes()+" bytes";checked[i]=es.get(i).active;}runOnUiThread(()->dialog=new AlertDialog.Builder(this).setTitle("Active bulk collections").setMultiChoiceItems(names,checked,(d,i,v)->checked[i]=v).setPositiveButton("Apply",(d,w)->run(()->{Set<String> ids=new HashSet<>();for(int i=0;i<es.size();i++)if(checked[i])ids.add(es.get(i).id);library.select(ids);runOnUiThread(()->status.setText(ids.size()+" active collections saved."));})).setNegativeButton("Cancel",null).show());});}
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==300&&result==RESULT_OK&&data!=null)run(()->{try(InputStream in=getContentResolver().openInputStream(data.getData())){input=in;ScaleLibrary.Entry e=library.install(in,()->cancelled);runOnUiThread(()->status.setText("Installed "+e.manifest.optString("label")+"; "+e.bytes()+" bytes."+(library.lastAdmissionPeak>ScaleLibrary.TARGET?" Update is above the 45 GB target but below the 50 GB hard limit.":"")));}finally{input=null;}});}
 @Override public void onDestroy(){cancelled=true;if(worker!=null)worker.interrupt();InputStream in=input;if(in!=null)new Thread(()->{try{in.close();}catch(Exception ignored){}}).start();super.onDestroy();}
}
