package org.pocketlore.app;
import java.io.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.*;import java.util.*;import java.util.function.BooleanSupplier;import java.util.zip.*;import org.json.*;
/** Durable, streaming bulk admission; no source rights or semantic support inferred from hashes. */
final class ScaleLibrary {
 static final long TARGET=45_000_000_000L,HARD=50_000_000_000L,RESERVE=256L*1024*1024;
 final File root;long lastTemporaryPeak;
 static final class Entry {final String id;final boolean active;final File directory;final JSONObject manifest;Entry(String id,boolean active,File dir,JSONObject m){this.id=id;this.active=active;directory=dir;manifest=m;}String kind(){return manifest.optString("kind");}long bytes(){return manifest.optLong("installed_bytes")+new File(directory,"manifest.json").length();}boolean mayGenerate(){return false;}}
 ScaleLibrary(File files)throws Exception{root=new File(files,"scale-library");if(!root.isDirectory()&&!root.mkdirs())throw new IOException("Cannot create bulk library");for(File f:Objects.requireNonNull(root.listFiles()))if(f.getName().startsWith("pending-"))removeTree(f);}
 static void check(boolean ok,String why)throws IOException{if(!ok)throw new IOException(why);}
 static void cancelled(BooleanSupplier c)throws IOException{if(c.getAsBoolean()||Thread.currentThread().isInterrupted())throw new InterruptedIOException("Bulk operation cancelled");}
 static String hex(byte[] b){StringBuilder out=new StringBuilder();for(byte v:b)out.append(String.format(Locale.ROOT,"%02x",v&255));return out.toString();}
 static String hash(File f,BooleanSupplier cancel)throws Exception{MessageDigest d=MessageDigest.getInstance("SHA-256");try(InputStream in=new FileInputStream(f)){byte[] b=new byte[65536];int n;while((n=in.read(b))!=-1){cancelled(cancel);d.update(b,0,n);}}return hex(d.digest());}
 static File safe(File parent,String name)throws Exception{check(name.matches("[A-Za-z0-9][A-Za-z0-9_./-]{0,180}")&&!name.contains(".."),"Unsafe bulk path");File f=new File(parent,name);check(f.getCanonicalPath().startsWith(parent.getCanonicalPath()+File.separator),"Escaped bulk path");return f;}
 static void removeTree(File f)throws IOException{if(Files.isSymbolicLink(f.toPath()))throw new IOException("Unexpected symlink");if(f.isDirectory())for(File c:Objects.requireNonNull(f.listFiles()))removeTree(c);Files.deleteIfExists(f.toPath());}
 static void write(File f,byte[] b)throws Exception{try(FileOutputStream out=new FileOutputStream(f)){out.write(b);out.getFD().sync();}}
 List<Entry> entries()throws Exception{File catalog=new File(root,"catalog.json");JSONArray rows=catalog.exists()?new JSONArray(new String(Files.readAllBytes(catalog.toPath()),StandardCharsets.UTF_8)):new JSONArray();check(rows.length()<=64,"Collection count limit");List<Entry> result=new ArrayList<>();Set<String> seen=new HashSet<>();for(int i=0;i<rows.length();i++){JSONObject r=rows.getJSONObject(i);String id=r.getString("id");check(id.matches("[a-f0-9]{64}")&&seen.add(id),"Invalid catalog identity");File dir=new File(root,id),m=new File(dir,"manifest.json");check(m.length()>0&&m.length()<=1024*1024&&hash(m,()->false).equals(id),"Catalog manifest integrity");JSONObject manifest=new JSONObject(new String(Files.readAllBytes(m.toPath()),StandardCharsets.UTF_8));validate(manifest);for(int j=0;j<manifest.getJSONArray("files").length();j++){JSONObject spec=manifest.getJSONArray("files").getJSONObject(j);check(safe(dir,spec.getString("path")).length()==spec.getLong("bytes"),"Installed file size drift");}result.add(new Entry(id,r.getBoolean("active"),dir,manifest));}return result;}
 private void commit(List<Entry> entries)throws Exception{JSONArray a=new JSONArray();for(Entry e:entries)a.put(new JSONObject().put("id",e.id).put("active",e.active));File stage=new File(root,"catalog.tmp");write(stage,a.toString().getBytes(StandardCharsets.UTF_8));Files.move(stage.toPath(),new File(root,"catalog.json").toPath(),StandardCopyOption.ATOMIC_MOVE,StandardCopyOption.REPLACE_EXISTING);}
 synchronized void select(Set<String> ids)throws Exception{List<Entry> es=entries(),next=new ArrayList<>();Set<String> found=new HashSet<>();for(Entry e:es){if(ids.contains(e.id))found.add(e.id);next.add(new Entry(e.id,ids.contains(e.id),e.directory,e.manifest));}check(found.equals(ids),"Unknown active collection");commit(next);}
 static void validate(JSONObject m)throws Exception{check(m.getInt("version")==1&&Set.of("wiki","places").contains(m.getString("kind")),"Unsupported bulk format");check(!m.getBoolean("generation_allowed"),"Bulk semantic authorization not implemented");check(!m.getString("rights_status").isEmpty()&&!m.getString("source_inventory_sha256").isEmpty(),"Missing provenance");JSONArray fs=m.getJSONArray("files");check(fs.length()>0&&fs.length()<=256,"File count");long total=0;Set<String> names=new HashSet<>();for(int i=0;i<fs.length();i++){JSONObject f=fs.getJSONObject(i);String name=f.getString("path");check(!name.equals("manifest.json")&&names.add(name),"Repeated/reserved file");long n=f.getLong("bytes");check(n>0&&n<=10_000_000_000L&&f.getString("sha256").matches("[a-f0-9]{64}"),"File admission");total=Math.addExact(total,n);}check(total<=HARD&&total==m.getLong("installed_bytes"),"Manifest byte accounting");}
 synchronized Entry install(InputStream input,BooleanSupplier cancel)throws Exception{cancelled(cancel);List<Entry> old=entries();File stage=Files.createTempDirectory(root.toPath(),"pending-").toFile();boolean moved=false;File destination=null;lastTemporaryPeak=0;
  try(ZipInputStream zip=new ZipInputStream(input)){ZipEntry first=zip.getNextEntry();check(first!=null&&first.getName().equals("manifest.json"),"Manifest must be first");ByteArrayOutputStream bytes=new ByteArrayOutputStream();byte[] buffer=new byte[65536];int n;while((n=zip.read(buffer))!=-1){cancelled(cancel);check(bytes.size()+n<=1024*1024,"Manifest bound");bytes.write(buffer,0,n);}byte[] raw=bytes.toByteArray();JSONObject m=new JSONObject(new String(raw,StandardCharsets.UTF_8));validate(m);String id=hex(MessageDigest.getInstance("SHA-256").digest(raw));for(Entry e:old)if(e.id.equals(id))return e;check(old.size()<64,"Collection count limit");long prior=0;for(Entry e:old)prior=Math.addExact(prior,e.bytes());check(Math.addExact(prior,Math.addExact(m.getLong("installed_bytes"),raw.length+1048576L))<=HARD,"Joint hard storage limit");ResourceStorage.requireSpace(m.getLong("installed_bytes")+raw.length,root.getUsableSpace());write(new File(stage,"manifest.json"),raw);long copied=raw.length;JSONArray files=m.getJSONArray("files");
   for(int i=0;i<files.length();i++){cancelled(cancel);JSONObject spec=files.getJSONObject(i);ZipEntry entry=zip.getNextEntry();check(entry!=null&&entry.getName().equals(spec.getString("path"))&&!entry.isDirectory(),"Manifest/archive order mismatch");File file=safe(stage,entry.getName());check(file.getParentFile().isDirectory()||file.getParentFile().mkdirs(),"Directory creation");MessageDigest d=MessageDigest.getInstance("SHA-256");long count=0;try(FileOutputStream out=new FileOutputStream(file)){while((n=zip.read(buffer))!=-1){cancelled(cancel);count+=n;check(count<=spec.getLong("bytes"),"Overlong file");out.write(buffer,0,n);d.update(buffer,0,n);copied+=n;lastTemporaryPeak=Math.max(lastTemporaryPeak,copied);}out.getFD().sync();}check(count==spec.getLong("bytes")&&hex(d.digest()).equals(spec.getString("sha256")),"Bulk file hash/length mismatch");}
   check(zip.getNextEntry()==null,"Unlisted archive entry");cancelled(cancel);destination=new File(root,id);check(!destination.exists(),"Uncatalogued edition exists");Files.move(stage.toPath(),destination.toPath(),StandardCopyOption.ATOMIC_MOVE);moved=true;Entry e=new Entry(id,true,destination,m);old.add(e);commit(old);return e;
  }catch(Exception|Error error){if(moved&&destination!=null)removeTree(destination);throw error;}finally{if(stage.exists())removeTree(stage);}
 }
}
