package org.pocketlore.app;
import java.io.*;import java.nio.charset.StandardCharsets;import java.security.*;import java.util.function.BooleanSupplier;
/** Stream decoded JSON strings from an already hash-verified record without materializing giant strings. */
final class SourceTextSlice {
 static int next(Reader r)throws IOException{int c=r.read();if(c<0)throw new EOFException("Truncated JSON source");return c;}
 static void string(Reader r,Writer out,BooleanSupplier cancel)throws Exception{int count=0;for(;;){if((count++&4095)==0)ScaleLibrary.cancelled(cancel);int c=next(r);if(c=='"')return;if(c=='\\'){c=next(r);switch(c){case '"':case '\\':case '/':break;case 'b':c='\b';break;case 'f':c='\f';break;case 'n':c='\n';break;case 'r':c='\r';break;case 't':c='\t';break;case 'u':c=0;for(int i=0;i<4;i++){int digit=Character.digit(next(r),16);if(digit<0)throw new IOException("Invalid source escape");c=c*16+digit;}break;default:throw new IOException("Invalid source escape");}}else if(c<32)throw new IOException("Invalid source control");if(out!=null)out.write(c);}}
 static void read(File file,ScaleWiki.Read result,String expected,BooleanSupplier cancel)throws Exception{MessageDigest digest=MessageDigest.getInstance("SHA-256");StringBuilder preview=new StringBuilder();long[] chars={0};boolean found=false;
 try(Reader r=new BufferedReader(new InputStreamReader(new FileInputStream(file),StandardCharsets.UTF_8),65536)){int depth=0,c;while((c=r.read())!=-1){ScaleLibrary.cancelled(cancel);if(c=='{'||c=='[')depth++;else if(c=='}'||c==']')depth--;else if(c=='"'){if(depth!=1){string(r,null,cancel);continue;}StringWriter key=new StringWriter();string(r,key,cancel);do{c=next(r);}while(Character.isWhitespace(c));if(c!=':')throw new IOException("Invalid source key");do{c=next(r);}while(Character.isWhitespace(c));if(c!='"'){if(c=='{'||c=='[')depth++;continue;}
 if(key.toString().equals("text")){ScaleLibrary.check(!found,"Repeated source text");found=true;OutputStream sink=new java.security.DigestOutputStream(new OutputStream(){public void write(int b){}public void write(byte[] b,int o,int n){}},digest);Writer utf=new BufferedWriter(new OutputStreamWriter(sink,StandardCharsets.UTF_8),8192);Writer capture=new Writer(){public void write(char[] b,int o,int n)throws IOException{utf.write(b,o,n);int keep=Math.min(n,64000-preview.length());if(keep>0)preview.append(b,o,keep);chars[0]+=n;}public void write(int ch)throws IOException{utf.write(ch);if(preview.length()<64000)preview.append((char)ch);chars[0]++;}public void flush()throws IOException{utf.flush();}public void close()throws IOException{utf.close();}};string(r,capture,cancel);capture.close();}
 else if(key.toString().equals("wikitext_scope")){StringWriter value=new StringWriter();string(r,value,cancel);result.wikitextScope=value.toString();}else string(r,null,cancel);
 }} }
 ScaleLibrary.check(found&&ScaleLibrary.hex(digest.digest()).equals(expected.toLowerCase(java.util.Locale.ROOT)),"Retained text checksum");result.text=preview.toString();result.previewTruncated=chars[0]>64000;
 }
}
