package org.pocketlore.app;
import android.app.*;import android.content.*;import android.os.Bundle;import android.widget.*;import java.io.*;import java.util.*;import java.util.concurrent.*;

/** Explicit offline source-inspection route, never a research-admission shortcut. */
public final class StructuredSourceActivity extends NotebookActivity {
 final ExecutorService reader=Executors.newSingleThreadExecutor(),closer=Executors.newSingleThreadExecutor();volatile boolean cancelled;volatile InputStream input;int epoch;File directory;LinearLayout page,results;EditText query;String edition="",currentText="",currentMetadata="";long article,position;boolean original;
 @Override public void onCreate(Bundle state){super.onCreate(state);directory=new File(getFilesDir(),"structured-sources");directory.mkdirs();page=ReaderUi.column(this);ReaderUi.screen(this,page,"Library");page.addView(ReaderUi.text(this,"Source inspection",26));page.addView(ReaderUi.text(this,"Read imported source text and original context. These sources are not approved for answers.",16));operation=ReaderUi.text(this,"",16);page.addView(operation);
  ReaderUi.button(this,page,"Import source collection",()->startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).addCategory(Intent.CATEGORY_OPENABLE).setType("*/*"),523));ReaderUi.button(this,page,"Cancel operation",()->{cancelled=true;epoch++;InputStream in=input;if(in!=null)closer.execute(()->{try{in.close();}catch(Exception ignored){}});message("Operation cancelled; saved editions retained.");});
  query=new EditText(this);ReaderUi.label(this,page,query,"Search selected source collection");page.addView(query);ReaderUi.button(this,page,"Search sources",()->search());ReaderUi.button(this,page,"Collections",this::collections);results=ReaderUi.column(this);page.addView(results);
  if(state!=null){edition=state.getString("edition","");article=state.getLong("article");position=state.getLong("position");original=state.getBoolean("original");query.setText(state.getString("query",""));}if(!edition.isEmpty()&&article>0)read();else collections();
 }
 interface Task{void run(int ticket)throws Exception;}
 void task(Task task){cancelled=false;int ticket=++epoch;reader.execute(()->{if(cancelled||ticket!=epoch||isDestroyed())return;try{task.run(ticket);}catch(Exception e){show(ticket,()->message("Source unavailable: "+e.getMessage()+". Existing sources are unchanged."));}});}
 void show(int ticket,Runnable r){runOnUiThread(()->{if(!isDestroyed()&&ticket==epoch&&!cancelled)r.run();});}
 void collections(){epoch++;results.removeAllViews();File[] files=directory.listFiles((d,n)->n.matches("[0-9a-f]{64}\\.json"));if(files==null)return;if(files.length>128){message("Collection list exceeds this reader’s current bound; all editions are retained.");return;}Arrays.sort(files);for(File f:files){String id=f.getName().substring(0,64);ReaderUi.button(this,results,"Source collection "+id.substring(0,12),()->{edition=id;article=0;position=0;list();});}if(files.length==0)results.addView(ReaderUi.text(this,"No structured source collections imported.",16));}
 void list(){task(ticket->{try(StructuredSource s=new StructuredSource(directory,edition)){List<String[]> rows=s.articles((int)position,()->cancelled||ticket!=epoch);show(ticket,()->{results.removeAllViews();for(String[] r:rows)ReaderUi.button(this,results,r[1],()->{article=Long.parseLong(r[0]);position=0;original=false;read();});ReaderUi.button(this,results,"Previous articles",()->{position=Math.max(0,position-20);list();});if(rows.size()==20)ReaderUi.button(this,results,"Next articles",()->{position+=20;list();});});}});}
 void search(){if(edition.isEmpty()){message("Choose a source collection first.");return;}String text=query.getText().toString();task(ticket->{try(StructuredSource s=new StructuredSource(directory,edition)){List<String[]> rows=s.search(text,()->cancelled||ticket!=epoch);show(ticket,()->{results.removeAllViews();if(rows.isEmpty())results.addView(ReaderUi.text(this,"No matching source text. This is not evidence of absence.",16));for(String[] r:rows)ReaderUi.button(this,results,r[2]+" — "+r[3],()->{article=Long.parseLong(r[0]);position=Long.parseLong(r[1]);original=false;read();});});}});}
 void read(){task(ticket->{try(StructuredSource s=new StructuredSource(directory,edition)){StructuredSource.Window window=s.window(article,position,original,()->cancelled||ticket!=epoch);String text=window.text,meta=s.metadata(article);show(ticket,()->{currentText=text;currentMetadata=meta;results.removeAllViews();TextView content=ReaderUi.text(this,text.isEmpty()?"End of source.":text,18);if(window.highlightStart>=0){android.text.SpannableString marked=new android.text.SpannableString(text);marked.setSpan(new android.text.style.BackgroundColorSpan(0xffffe69a),window.highlightStart,window.highlightEnd,android.text.Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);content.setText(marked);}content.setTextIsSelectable(true);results.addView(content);ReaderUi.button(this,results,"Source identity and rights",()->ReaderUi.reader(this,"Source identity and rights",meta));ReaderUi.button(this,results,original?"Read source structure":"Inspect original HTML",()->{original=!original;position=original?window.originalStart:0;read();});ReaderUi.button(this,results,"Previous source window",()->{position=window.previous;read();});if(!text.isEmpty())ReaderUi.button(this,results,"Next source window",()->{position=window.next;read();});ReaderUi.button(this,results,"Export this source window",()->{NotebookStore.Entry e=new NotebookStore.Entry();e.kind="source";e.title="Source inspection window";e.question="";e.body=currentText;e.provenance=currentMetadata;e.note="";e.created=System.currentTimeMillis();export(Collections.singletonList(e),false);});});}});}
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==523&&result==RESULT_OK&&data!=null)task(ticket->{try(InputStream in=getContentResolver().openInputStream(data.getData())){input=in;String id=StructuredSource.install(in,directory,()->cancelled||ticket!=epoch);show(ticket,()->{edition=id;position=0;article=0;message("Source collection imported for inspection only.");list();});}finally{input=null;}});}
 @Override public void onSaveInstanceState(Bundle b){super.onSaveInstanceState(b);b.putString("edition",edition);b.putLong("article",article);b.putLong("position",position);b.putBoolean("original",original);b.putString("query",query.getText().toString());}
 @Override public void onDestroy(){cancelled=true;epoch++;reader.shutdownNow();InputStream in=input;if(in!=null)closer.execute(()->{try{in.close();}catch(Exception ignored){}});closer.shutdown();super.onDestroy();}
}
