package org.pocketlore.app;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;
import java.util.function.BooleanSupplier;
import java.util.zip.*;
import org.json.*;

/** Separate inspection-only format. This class cannot return answer evidence. */
final class StructuredSource implements AutoCloseable {
 static final long MAX=64L*1024*1024;
 static final String EXPECTED_SCHEMA="[[\"article_nodes\",\"CREATE INDEX article_nodes ON nodes(article,id)\"],[\"articles\",\"CREATE TABLE articles(id INTEGER PRIMARY KEY,title TEXT NOT NULL,metadata TEXT NOT NULL,original_sha TEXT NOT NULL,html_sha TEXT NOT NULL,original_bytes INTEGER NOT NULL,html_units INTEGER NOT NULL)\"],[\"dispositions\",\"CREATE TABLE dispositions(sequence INTEGER PRIMARY KEY,page INTEGER,revision INTEGER,outcome TEXT NOT NULL,raw_sha TEXT NOT NULL)\"],[\"html_chunks\",\"CREATE TABLE html_chunks(article INTEGER NOT NULL,start INTEGER NOT NULL,end INTEGER NOT NULL,text TEXT NOT NULL,sha TEXT NOT NULL,PRIMARY KEY(article,start))\"],[\"nodes\",\"CREATE TABLE nodes(id INTEGER PRIMARY KEY,article INTEGER NOT NULL,parent INTEGER NOT NULL,tag TEXT NOT NULL,attrs TEXT NOT NULL,start INTEGER NOT NULL,end INTEGER NOT NULL,text TEXT NOT NULL,kind TEXT NOT NULL)\"],[\"originals\",\"CREATE TABLE originals(article INTEGER NOT NULL,part INTEGER NOT NULL,bytes BLOB NOT NULL,sha TEXT NOT NULL,PRIMARY KEY(article,part))\"],[\"parent_nodes\",\"CREATE INDEX parent_nodes ON nodes(article,parent,id)\"],[\"search\",\"CREATE VIRTUAL TABLE search USING fts4(text,content=nodes,tokenize=unicode61)\"],[\"search_docsize\",\"CREATE TABLE 'search_docsize'(docid INTEGER PRIMARY KEY, size BLOB)\"],[\"search_segdir\",\"CREATE TABLE 'search_segdir'(level INTEGER,idx INTEGER,start_block INTEGER,leaves_end_block INTEGER,end_block INTEGER,root BLOB,PRIMARY KEY(level, idx))\"],[\"search_segments\",\"CREATE TABLE 'search_segments'(blockid INTEGER PRIMARY KEY, block BLOB)\"],[\"search_stat\",\"CREATE TABLE 'search_stat'(id INTEGER PRIMARY KEY, value BLOB)\"]]";
 static final String FORMAT="pocketlore-structured-source-v1";
 static boolean same(Object a,Object b)throws Exception{if(a instanceof JSONObject&&b instanceof JSONObject){JSONObject x=(JSONObject)a,y=(JSONObject)b;if(x.length()!=y.length())return false;Iterator<String> keys=x.keys();while(keys.hasNext()){String k=keys.next();if(!y.has(k)||!same(x.get(k),y.get(k)))return false;}return true;}if(a instanceof JSONArray&&b instanceof JSONArray){JSONArray x=(JSONArray)a,y=(JSONArray)b;if(x.length()!=y.length())return false;for(int i=0;i<x.length();i++)if(!same(x.get(i),y.get(i)))return false;return true;}return a.toString().equals(b.toString());}
 static final String SEARCH="CREATE VIRTUAL TABLE search USING fts4(text,content=nodes,tokenize=unicode61)";
 final SQLiteDatabase db;final String identity;final File directory;
 StructuredSource(File dir,String hash)throws Exception{
  require(hash.matches("[0-9a-f]{64}"),"Source identity invalid");directory=dir;identity=hash;
  File path=new File(dir,hash+".sqlite");require(path.isFile()&&path.length()<=MAX,"Source index missing");
  File mf=new File(dir,hash+".json");require(mf.length()>0&&mf.length()<2*1024*1024,"Manifest bound");JSONObject manifest=new JSONObject(new String(Files.readAllBytes(mf.toPath()),StandardCharsets.UTF_8));
  require(FORMAT.equals(manifest.getString("format"))&&!manifest.getBoolean("source_admission_established"),"Unsupported source admission");
  require(BroadPack.hash(path).equals(manifest.getString("db_sha256")),"Source index changed");db=open(path);require(db.getVersion()==523,"Unsupported structure schema");
 }
 static SQLiteDatabase open(File path){SQLiteDatabase d=SQLiteDatabase.openDatabase(path.getPath(),null,SQLiteDatabase.OPEN_READONLY|SQLiteDatabase.NO_LOCALIZED_COLLATORS);d.rawQuery("PRAGMA cache_size=-2048",null).close();d.rawQuery("PRAGMA mmap_size=0",null).close();return d;}
 static void require(boolean b,String m)throws IOException{if(!b)throw new IOException(m);}
 static void check(BooleanSupplier c)throws IOException{if(c.getAsBoolean()||Thread.currentThread().isInterrupted())throw new InterruptedIOException("Source operation cancelled");}
 static byte[] bytes(InputStream in,int max,BooleanSupplier c)throws Exception{ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1){check(c);require(out.size()+n<=max,"Source size bound");out.write(b,0,n);}return out.toByteArray();}
 static String decodeEntities(String value){java.util.regex.Matcher matcher=SourceStructureParser.ENTITY.matcher(value);StringBuffer out=new StringBuffer();while(matcher.find())matcher.appendReplacement(out,java.util.regex.Matcher.quoteReplacement(android.text.Html.fromHtml(matcher.group(),android.text.Html.FROM_HTML_MODE_LEGACY).toString()));matcher.appendTail(out);return out.toString();}
 static String hash(byte[] b)throws Exception{return KnowledgePack.hash(b);}
 static synchronized String install(InputStream in,File dir,BooleanSupplier cancel)throws Exception{
  require(dir.isDirectory()||dir.mkdirs(),"Source directory unavailable");File stage=new File(dir,UUID.randomUUID()+".partial"),index=new File(dir,UUID.randomUUID()+".partial");List<File> owned=new ArrayList<>();boolean published=false;
  try(ResourceStorage.Reservation reservation=ResourceStorage.reserve(ResourceStorage.stagePeak(3*MAX))){
   ResourceStorage.copy(in,stage,MAX,cancel);String id=BroadPack.hash(stage);JSONObject m;
   try(ZipFile z=new ZipFile(stage)){
    require(z.size()==4,"Unexpected source archive members");ZipEntry entry=z.getEntry("manifest.json");require(entry!=null,"Missing source manifest");m=new JSONObject(new String(bytes(z.getInputStream(entry),2*1024*1024,cancel),StandardCharsets.UTF_8));
    require(FORMAT.equals(m.getString("format"))&&m.getInt("schema_version")==523&&!m.getBoolean("source_admission_established"),"Unsupported source format or promotion");
    String[] names={"CC-BY-SA-3.0","CC-BY-SA-4.0"},pins={"3f941b3b89cf7b8370ceb83cc76d2120d471b58735d8ca60238a751a48d7f72f","28a9529c7d0bb4dc51f4bf5c116a3d16ef247a052f7591466768ddf563fd1cf5"};
    for(int i=0;i<2;i++){ZipEntry legal=z.getEntry(names[i]+".txt");require(legal!=null,"Offline license missing");require(hash(bytes(z.getInputStream(legal),131072,cancel)).equals(pins[i])&&m.getJSONObject("licenses").getString(names[i]).equals(pins[i]),"Offline license changed");}
    entry=z.getEntry("index.sqlite");require(entry!=null&&entry.getSize()==m.getLong("db_bytes")&&entry.getSize()<=MAX,"Index size invalid");try(InputStream input=z.getInputStream(entry)){ResourceStorage.copy(input,index,MAX,cancel);}
   }
   require(BroadPack.hash(index).equals(m.getString("db_sha256")),"Index hash mismatch");validate(index,m,cancel);require(BroadPack.hash(index).equals(m.getString("db_sha256")),"Validation changed source bytes");check(cancel);
   // Catalog discovery uses only the final manifest. Failed import leaves old editions untouched.
   File target=new File(dir,id+".json");if(target.exists()){try(StructuredSource old=new StructuredSource(dir,id)){}return id;}
   require(!new File(dir,id+".sqlite").exists()&&!new File(dir,id+".plsource").exists(),"Interrupted edition retained; recovery required");
   Files.move(index.toPath(),new File(dir,id+".sqlite").toPath(),StandardCopyOption.ATOMIC_MOVE);owned.add(new File(dir,id+".sqlite"));
   Files.move(stage.toPath(),new File(dir,id+".plsource").toPath(),StandardCopyOption.ATOMIC_MOVE);owned.add(new File(dir,id+".plsource"));
   File meta=new File(dir,id+".json.partial");require(!meta.exists(),"Retained interrupted manifest");owned.add(meta);try(FileOutputStream out=new FileOutputStream(meta)){out.write(m.toString().getBytes(StandardCharsets.UTF_8));out.getFD().sync();}check(cancel);Files.move(meta.toPath(),target.toPath(),StandardCopyOption.ATOMIC_MOVE);published=true;return id;
  }finally{stage.delete();index.delete();if(!published)for(File f:owned)f.delete();}
 }
 static void validate(File path,JSONObject m,BooleanSupplier cancel)throws Exception{

  try(SQLiteDatabase d=open(path)){
   require(d.getVersion()==523,"Unsupported source schema");try(Cursor c=d.rawQuery("SELECT sql FROM sqlite_master WHERE name='search'",null)){require(c.moveToFirst()&&SEARCH.equals(c.getString(0)),"Unsupported FTS schema/tokenizer");}
   try(Cursor c=d.rawQuery("SELECT count(*) FROM sqlite_master WHERE type NOT IN ('table','index')",null)){c.moveToFirst();require(c.getInt(0)==0,"Executable schema denied");}
   try(Cursor c=d.rawQuery("PRAGMA integrity_check",null)){require(c.moveToFirst()&&c.getString(0).equals("ok"),"Corrupt source index");}
   JSONArray schema=m.getJSONArray("schema");require(same(schema,new JSONArray(EXPECTED_SCHEMA)),"Unrecognized schema declaration");int count=0;try(Cursor c=d.rawQuery("SELECT name,sql FROM sqlite_master WHERE sql IS NOT NULL ORDER BY name",null)){while(c.moveToNext()){check(cancel);require(count<schema.length()&&c.getString(0).equals(schema.getJSONArray(count).getString(0))&&c.getString(1).equals(schema.getJSONArray(count).getString(1)),"Schema identity changed");count++;}}require(count==schema.length(),"Missing schema");
   count=0;try(Cursor a=d.rawQuery("SELECT id,title,metadata,original_sha,html_sha,original_bytes,html_units FROM articles ORDER BY id",null)){while(a.moveToNext()){
    check(cancel);long id=a.getLong(0);require(a.getLong(5)>0&&a.getLong(5)<=16000000&&a.getLong(6)<=4000000,"Article import bound");ByteArrayOutputStream raw=new ByteArrayOutputStream();int part=0;
    try(Cursor c=d.rawQuery("SELECT part,bytes,sha FROM originals WHERE article=? ORDER BY part",new String[]{""+id})){while(c.moveToNext()){check(cancel);byte[] b=c.getBlob(1);require(c.getInt(0)==part++&&b.length>0&&b.length<=32768&&hash(b).equals(c.getString(2))&&raw.size()+b.length<=a.getLong(5),"Original capsule corrupt");raw.write(b);}}
    require(raw.size()==a.getLong(5)&&hash(raw.toByteArray()).equals(a.getString(3)),"Original identity mismatch");JSONObject original=new JSONObject(raw.toString("UTF-8"));String html=original.getJSONObject("article_body").getString("html");require(html.length()==a.getLong(6)&&html.getBytes(StandardCharsets.UTF_8).length<=4000000&&hash(html.getBytes(StandardCharsets.UTF_8)).equals(a.getString(4)),"Original HTML changed");
    JSONObject meta=new JSONObject(a.getString(2));require(!meta.getBoolean("source_admission_established")&&original.getLong("identifier")==id&&original.getString("name").equals(a.getString(1)),"Metadata identity mismatch");
    for(String key:new String[]{"name","identifier","date_modified","url","version","license"})require(same(meta.get(key),original.get(key)),"Original metadata changed: "+key);
    JSONArray licenses=original.getJSONArray("license");require(licenses.length()==1,"Unreviewed license list");JSONObject license=licenses.getJSONObject(0);String version=license.getString("identifier");require((version.equals("CC-BY-SA-3.0")||version.equals("CC-BY-SA-4.0"))&&license.getString("url").equals("https://creativecommons.org/licenses/by-sa/"+(version.endsWith("3.0")?"3.0":"4.0")+"/"),"License URI invalid");
    int end=0;try(Cursor c=d.rawQuery("SELECT start,end,text,sha FROM html_chunks WHERE article=? ORDER BY start",new String[]{""+id})){while(c.moveToNext()){check(cancel);String s=c.getString(2);require(c.getInt(0)==end&&c.getInt(1)==end+s.length()&&s.length()<=8192&&html.startsWith(s,end)&&hash(s.getBytes(StandardCharsets.UTF_8)).equals(c.getString(3)),"HTML window mismatch");end+=s.length();}}require(end==html.length(),"Missing original context");
    List<SourceStructureParser.Node> expected=SourceStructureParser.parse(html,StructuredSource::decodeEntities,cancel);int nodeIndex=0;long base=0;
    long previous=0;try(Cursor c=d.rawQuery("SELECT id,parent,tag,attrs,start,end,text,kind FROM nodes WHERE article=? ORDER BY id",new String[]{""+id})){while(c.moveToNext()){check(cancel);require(nodeIndex<expected.size(),"Extra projection node");if(nodeIndex==0)base=c.getLong(0)-1;SourceStructureParser.Node expectedNode=expected.get(nodeIndex++);
     require(c.getLong(0)==base+nodeIndex&&c.getLong(1)==(expectedNode.parent==0?0:base+expectedNode.parent)&&c.getString(2).equals(expectedNode.tag)&&same(new JSONObject(c.getString(3)),new JSONObject(expectedNode.attrs))&&c.getInt(4)==expectedNode.start&&c.getInt(5)==expectedNode.end&&c.getString(6).equals(expectedNode.text)&&c.getString(7).equals(expectedNode.kind),"Complete original tree mismatch");int s=c.getInt(4),e=c.getInt(5);String text=c.getString(6),kind=c.getString(7);require(c.getLong(0)>previous&&s>=0&&e>=s&&e<=html.length()&&text.length()<=4096&&c.getString(3).length()<=65536,"Node bound");previous=c.getLong(0);require(!(s>0&&Character.isLowSurrogate(html.charAt(s)))&&!(e<html.length()&&Character.isLowSurrogate(html.charAt(e))),"Split UTF16 character");String fragment=html.substring(s,e);if(kind.equals("element"))require(fragment.matches("(?s)<"+java.util.regex.Pattern.quote(c.getString(2))+"(?:\\s|/?>).*"),"Element source mismatch");
     if(kind.equals("literal"))require(text.equals(fragment),"Literal mapping mismatch");else if(kind.equals("entity"))require(text.equals(android.text.Html.fromHtml(fragment,android.text.Html.FROM_HTML_MODE_LEGACY).toString()),"Entity mapping mismatch");else require(text.isEmpty()&&(kind.equals("element")||kind.equals("omitted-unsafe")),"Unknown projection kind");
     if(c.getLong(1)!=0)try(Cursor parent=d.rawQuery("SELECT start,end FROM nodes WHERE id=? AND article=?",new String[]{c.getString(1),""+id})){require(parent.moveToFirst()&&c.getLong(1)<c.getLong(0)&&parent.getInt(0)<=s&&parent.getInt(1)>=e,"Parent context lost");}
    }}require(nodeIndex==expected.size(),"Omitted projection nodes");count++;
   }}require(count==m.getInt("articles")&&count>0,"Article count mismatch");
   try(Cursor c=d.rawQuery("SELECT count(*) FROM nodes",null)){c.moveToFirst();require(c.getInt(0)==m.getInt("nodes"),"Node count mismatch");}
   try(Cursor c=d.rawQuery("SELECT count(*) FROM nodes n LEFT JOIN articles a ON a.id=n.article WHERE a.id IS NULL",null)){c.moveToFirst();require(c.getInt(0)==0,"Orphan nodes denied");}
  }
  try(SQLiteDatabase integrity=SQLiteDatabase.openDatabase(path.getPath(),null,SQLiteDatabase.OPEN_READWRITE|SQLiteDatabase.NO_LOCALIZED_COLLATORS)){integrity.execSQL("INSERT INTO search(search) VALUES('integrity-check')");}
 }
 List<String[]> articles(int offset,BooleanSupplier cancel)throws Exception{List<String[]> out=new ArrayList<>();try(Cursor c=db.rawQuery("SELECT id,title FROM articles ORDER BY id LIMIT 20 OFFSET ?",new String[]{""+Math.max(0,offset)})){while(c.moveToNext()){check(cancel);out.add(new String[]{c.getString(0),c.getString(1)});}}return out;}
 List<String[]> search(String query,BooleanSupplier cancel)throws Exception{List<String[]> out=new ArrayList<>();List<String> terms=ResearchEngine.tokenize(query);if(terms.isEmpty())return out;StringBuilder q=new StringBuilder();for(String t:terms.subList(0,Math.min(12,terms.size()))){if(q.length()>0)q.append(" AND ");q.append('"').append(t.replace("\"","\"\"")).append('"');}try(Cursor c=db.rawQuery("SELECT n.article,n.id,a.title,n.text FROM search JOIN nodes n ON n.id=search.docid JOIN articles a ON a.id=n.article WHERE search MATCH ? ORDER BY n.article,n.id LIMIT 20",new String[]{q.toString()})){while(c.moveToNext()){check(cancel);out.add(new String[]{c.getString(0),c.getString(1),c.getString(2),c.getString(3)});}}return out;}
 String metadata(long article)throws Exception{try(Cursor c=db.rawQuery("SELECT title,metadata,original_sha,html_sha FROM articles WHERE id=?",new String[]{""+article})){require(c.moveToFirst(),"Article missing");return c.getString(0)+"\nInspection only · Source text, not a generated answer\nEdition SHA256: "+identity+"\nOriginal JSON SHA256: "+c.getString(2)+"\nHTML SHA256: "+c.getString(3)+"\n"+new JSONObject(c.getString(1)).toString(2);}}
 static final class Window {String text;long start,next,previous,originalStart;int highlightStart=-1,highlightEnd=-1;}
 Window window(long article,long first,boolean original,BooleanSupplier cancel)throws Exception{
  Window w=new Window();StringBuilder out=new StringBuilder();w.previous=0;w.next=first;
  if(original){try(Cursor c=db.rawQuery("SELECT start,end,text FROM html_chunks WHERE article=? AND end>? ORDER BY start LIMIT 1",new String[]{""+article,""+first})){if(c.moveToFirst()){w.start=c.getLong(0);w.next=c.getLong(1);out.append("Original HTML · inert text · UTF16 [").append(w.start).append(',').append(w.next).append(")\n").append(c.getString(2));}}try(Cursor c=db.rawQuery("SELECT start FROM html_chunks WHERE article=? AND start<? ORDER BY start DESC LIMIT 1",new String[]{""+article,""+w.start})){if(c.moveToFirst())w.previous=c.getLong(0);}}
  else {boolean initial=true;try(Cursor c=db.rawQuery("SELECT id,parent,tag,attrs,start,end,text,kind FROM nodes WHERE article=? AND id>=? ORDER BY id LIMIT 40",new String[]{""+article,""+first})){while(c.moveToNext()){check(cancel);if(initial){w.start=c.getLong(0);w.originalStart=c.getLong(4);initial=false;long parent=c.getLong(1);int depth=0;List<String> context=new ArrayList<>();while(parent!=0){require(depth++<64,"Context depth");try(Cursor a=db.rawQuery("SELECT parent,tag,start,end FROM nodes WHERE article=? AND id=?",new String[]{""+article,""+parent})){require(a.moveToFirst(),"Missing source context");context.add(a.getString(1)+" ["+a.getInt(2)+","+a.getInt(3)+")");parent=a.getLong(0);}}Collections.reverse(context);out.append("Exact source context: ").append(context).append("\n");
    long ancestor=c.getLong(1);for(int step=0;ancestor!=0&&step<64;step++){try(Cursor a=db.rawQuery("SELECT parent,tag,start,end FROM nodes WHERE article=? AND id=?",new String[]{""+article,""+ancestor})){require(a.moveToFirst(),"Missing context");String tag=a.getString(1);if(tag.equals("tr")||tag.equals("table")){String wanted=tag.equals("tr")?"th":"caption";try(Cursor head=db.rawQuery("SELECT start,end FROM nodes WHERE article=? AND tag=? AND parent=? ORDER BY id LIMIT 16",new String[]{""+article,wanted,""+ancestor})){while(head.moveToNext()){out.append(wanted.equals("th")?"Row header context: ":"Table caption context: ");int total=0;try(Cursor h=db.rawQuery("SELECT text FROM nodes WHERE article=? AND start>=? AND end<=? AND kind IN ('literal','entity') ORDER BY id LIMIT 32",new String[]{""+article,head.getString(0),head.getString(1)})){while(h.moveToNext()){check(cancel);String t=h.getString(0);if(total+t.length()>8192){out.append("[Continue in original context]");break;}out.append(t);total+=t.length();}}out.append('\n');}}}ancestor=a.getLong(0);}}
}
   JSONObject attrs=new JSONObject(c.getString(3));if(attrs.has("rowspan")||attrs.has("colspan"))out.append("Source cell span: rows ").append(attrs.optString("rowspan","1")).append(", columns ").append(attrs.optString("colspan","1")).append('\n');if(attrs.has("id"))out.append("Source anchor: ").append(attrs.optString("id")).append('\n');if(attrs.has("href"))out.append("Reference address (not independently verified): ").append(attrs.optString("href")).append('\n');w.next=c.getLong(0)+1;String tag=c.getString(2);String label=tag.equals("th")?"Header: ":tag.equals("td")?"Cell: ":tag.equals("tr")?"Table row":tag.equals("caption")?"Table caption: ":tag.equals("math")?"Mathematical source — inspect original notation":tag.equals("blockquote")||tag.equals("q")?"Quotation — additional rights may apply":tag.matches("h[1-6]")?"Section":tag.equals("table")?"Table":tag.equals("li")?"• ":"";if(!label.isEmpty())out.append("\n").append(label).append("\n");if(c.getLong(0)==first&&!c.getString(6).isEmpty())w.highlightStart=out.length();out.append(c.getString(7).equals("omitted-unsafe")?"":c.getString(6));if(c.getLong(0)==first&&w.highlightStart>=0)w.highlightEnd=out.length();out.append('\n');
  }}try(Cursor c=db.rawQuery("SELECT id FROM nodes WHERE article=? AND id<? ORDER BY id DESC LIMIT 40",new String[]{""+article,""+w.start})){while(c.moveToNext())w.previous=c.getLong(0);}}
  check(cancel);w.text=out.toString();return w;
 }
 public void close(){db.close();}
}
