package org.pocketlore.app;
import android.app.Instrumentation;import android.os.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;import org.json.*;import java.util.concurrent.atomic.AtomicInteger;
/** Real installed shard checks. Inputs are project-owned fixtures, never user collections. */
public final class ScaleIntegrationInstrumentation extends Instrumentation {
 Bundle args;JSONObject report=new JSONObject();File files;
 @Override public void onCreate(Bundle b){super.onCreate(b);args=b;start();}
 void put(String k,Object v)throws Exception{report.put(k,v);save();}
 void save()throws Exception{ScaleLibrary.write(new File(files,"scale-observation-"+args.getString("mode","inspect")+".json"),(report.toString(2)+"\n").getBytes(StandardCharsets.UTF_8));}
 JSONObject memory()throws Exception{Debug.MemoryInfo m=new Debug.MemoryInfo();Debug.getMemoryInfo(m);return new JSONObject().put("pss_kib",m.getTotalPss()).put("private_dirty_kib",m.getTotalPrivateDirty()).put("java_used_bytes",Runtime.getRuntime().totalMemory()-Runtime.getRuntime().freeMemory()).put("native_heap_bytes",Debug.getNativeHeapAllocatedSize());}
 void require(boolean value,String why){if(!value)throw new AssertionError(why);}
 @Override public void onStart(){files=getTargetContext().getFilesDir();Bundle result=new Bundle();long start=SystemClock.elapsedRealtime();try{put("environment","Android x86_64 emulator-5560; not physical hardware");put("before",memory());put("sqlite_identity",NativeIndex.identity());ScaleLibrary lib=new ScaleLibrary(files);String mode=args.getString("mode","inspect");
 if(mode.equals("import")){File archive=new File(files,args.getString("archive"));put("archive_bytes",archive.length());put("archive_sha256",ScaleLibrary.hash(archive,()->false));long t=SystemClock.elapsedRealtime();ScaleLibrary.Entry e;try(InputStream in=new FileInputStream(archive)){e=lib.install(in,()->false);}put("import_ms",SystemClock.elapsedRealtime()-t);put("edition",e.id);put("installed_bytes",e.bytes());put("temporary_bytes",lib.lastTemporaryPeak);put("may_generate",e.mayGenerate());require(!e.mayGenerate(),"unreviewed source generation");}
 else if(mode.equals("inspect")){JSONArray queries=new JSONArray();for(ScaleLibrary.Entry e:lib.entries()){require(!e.mayGenerate(),"source rights gate");if(e.kind().equals("wiki")){for(String q:new String[]{"Acid","Cooking","Absolute value","Algae","Transport in Belgium","Binary search","Constitution","Athens"}){long t=SystemClock.elapsedRealtime();List<ScaleWiki.Hit> hits=ScaleWiki.search(e,q,()->false);JSONArray titles=new JSONArray();for(ScaleWiki.Hit h:hits)titles.put(h.title);JSONObject observation=new JSONObject().put("query",q).put("titles",titles).put("ms",SystemClock.elapsedRealtime()-t);if(!hits.isEmpty()){ScaleWiki.Hit h=hits.get(0);ScaleWiki.Read r=ScaleWiki.read(h,getTargetContext().getCacheDir(),()->false);observation.put("source_identity",h.identity()).put("source_preview",r.text.substring(0,Math.min(500,r.text.length()))).put("raw_block_bytes",r.rawBlockBytes);}queries.put(observation);put("wiki_queries",queries);}
 ScaleWiki.Hit large=ScaleWiki.byId(e,"000_00000","79374590",()->false);put("before_oversized",memory());long t=SystemClock.elapsedRealtime();ScaleWiki.Read r=ScaleWiki.read(large,getTargetContext().getCacheDir(),()->false);put("oversized",new JSONObject().put("title",large.title).put("raw_block_bytes",r.rawBlockBytes).put("record_bytes",r.recordBytes).put("temporary_bytes",r.temporaryBytes).put("ms",SystemClock.elapsedRealtime()-t).put("memory_after",memory()).put("preview_truncated",r.previewTruncated));require(r.rawBlockBytes>8*1024*1024,"not oversized fixture");AtomicInteger polls=new AtomicInteger();t=SystemClock.elapsedRealtime();try{ScaleWiki.read(large,getTargetContext().getCacheDir(),()->polls.incrementAndGet()>10);throw new AssertionError("read cancellation ignored");}catch(InterruptedIOException expected){put("large_read_cancel_ms",SystemClock.elapsedRealtime()-t);}require(getTargetContext().getCacheDir().listFiles((d,n)->n.startsWith("scale-record-")).length==0,"stale source staging");
 try{NativeIndex.rows(ScaleWiki.database(e,"000_00000").getPath(),"DELETE FROM articles",new String[]{},1,()->false);throw new AssertionError("write accepted");}catch(IOException expected){put("readonly_rejection",expected.toString());}
 }else{JSONArray cities=new JSONArray();for(String name:new String[]{"Auckland","Berlin","Buenos Aires","Cairo","Cape Town","Istanbul","Lagos","London","Los Angeles","Mexico City","Mumbai","Nairobi","New York","Paris","Sao Paulo","Seoul","Singapore","Sydney","Tokyo","Toronto"}){long t=SystemClock.elapsedRealtime();List<ScalePlaces.City> cs=ScalePlaces.cities(e,name,()->false);JSONObject row=new JSONObject().put("query",name).put("city_matches",cs.size());if(!cs.isEmpty()){ScalePlaces.City c=cs.get(0);List<ScalePlaces.Hit> hs=ScalePlaces.nearby(e,c.lat,c.lon,1,null,()->false);row.put("city_id",c.id).put("lat",c.lat).put("lon",c.lon).put("places",hs.size());if(!hs.isEmpty())row.put("source",ScalePlaces.detail(hs.get(0),()->false));}row.put("ms",SystemClock.elapsedRealtime()-t);cities.put(row);put("cities",cities);}ScalePlaces.City c=ScalePlaces.cities(e,"London",()->false).get(0);require(ScalePlaces.nearby(e,c.lat,c.lon,1,"nonexistentcategory300",()->false).isEmpty(),"absent category leaked");put("absent_category","withheld: no matching source category");}}
 Set<String> all=new HashSet<>();for(ScaleLibrary.Entry e:lib.entries())all.add(e.id);lib.select(Collections.emptySet());require(new ScaleLibrary(files).entries().stream().noneMatch(e->e.active),"disabled restart");lib.select(all);require(new ScaleLibrary(files).entries().stream().allMatch(e->e.active),"active restart");put("active_restart_count",all.size());
 }put("after",memory());put("elapsed_ms",SystemClock.elapsedRealtime()-start);put("status","PASS");result.putString("report",report.toString());finish(-1,result);
 }catch(Throwable error){try{put("status","FAIL");put("error",error.toString());}catch(Exception ignored){}result.putString("error",error.toString());finish(1,result);}}
}
