package org.pocketlore.app;
import android.app.Instrumentation;import android.os.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;import org.json.*;import java.util.concurrent.atomic.AtomicInteger;
/** Real installed shard checks. Inputs are project-owned fixtures, never user collections. */
public final class ScaleIntegrationInstrumentation extends Instrumentation {
 Bundle args;JSONObject report=new JSONObject();File files;
 @Override public void onCreate(Bundle b){super.onCreate(b);args=b;start();}
 void put(String k,Object v)throws Exception{report.put(k,v);save();}
 void save()throws Exception{ScaleLibrary.write(new File(files,"scale-observation-"+args.getString("mode","inspect")+".json"),(report.toString(2)+"\n").getBytes(StandardCharsets.UTF_8));}
 JSONObject memory()throws Exception{Debug.MemoryInfo m=new Debug.MemoryInfo();Debug.getMemoryInfo(m);return new JSONObject().put("pss_kib",m.getTotalPss()).put("private_dirty_kib",m.getTotalPrivateDirty()).put("java_used_bytes",Runtime.getRuntime().totalMemory()-Runtime.getRuntime().freeMemory()).put("native_heap_bytes",Debug.getNativeHeapAllocatedSize()).put("proc_status",new String(java.nio.file.Files.readAllBytes(new File("/proc/self/status").toPath()),StandardCharsets.UTF_8));}
 void waitWorker(ScaleActivity activity)throws Exception{long deadline=SystemClock.elapsedRealtime()+60000;while(activity.worker!=null&&activity.worker.isAlive()){if(SystemClock.elapsedRealtime()>deadline)throw new AssertionError("UI worker deadline");Thread.sleep(20);}waitForIdleSync();}
 android.widget.Button button(android.view.View view,String label){if(view instanceof android.widget.Button&&((android.widget.Button)view).getText().toString().equals(label))return (android.widget.Button)view;if(view instanceof android.view.ViewGroup){android.view.ViewGroup group=(android.view.ViewGroup)view;for(int i=0;i<group.getChildCount();i++){android.widget.Button b=button(group.getChildAt(i),label);if(b!=null)return b;}}return null;}
 String visibleText(android.view.View v){StringBuilder s=new StringBuilder();if(v instanceof android.widget.TextView)s.append(((android.widget.TextView)v).getText()).append("\n");if(v instanceof android.view.ViewGroup){android.view.ViewGroup g=(android.view.ViewGroup)v;for(int i=0;i<g.getChildCount();i++)s.append(visibleText(g.getChildAt(i)));}return s.toString();}
 void require(boolean value,String why){if(!value)throw new AssertionError(why);}
 @Override public void onStart(){files=getTargetContext().getFilesDir();Bundle result=new Bundle();long start=SystemClock.elapsedRealtime();try{put("environment","Android x86_64 emulator-5560; not physical hardware");put("before",memory());put("sqlite_identity",NativeIndex.identity());ScaleLibrary lib=new ScaleLibrary(files);String mode=args.getString("mode","inspect");
 if(mode.equals("import")){File archive=new File(files,args.getString("archive"));put("archive_bytes",archive.length());put("archive_sha256",ScaleLibrary.hash(archive,()->false));long t=SystemClock.elapsedRealtime();ScaleLibrary.Entry e;try(InputStream in=new FileInputStream(archive)){e=lib.install(in,()->false);}put("import_ms",SystemClock.elapsedRealtime()-t);put("edition",e.id);put("installed_bytes",e.bytes());put("temporary_bytes",lib.lastTemporaryPeak);put("may_generate",e.mayGenerate());require(!e.mayGenerate(),"unreviewed source generation");}
 else if(mode.equals("ui")){
 ScaleActivity activity=(ScaleActivity)startActivitySync(new android.content.Intent(getTargetContext(),ScaleActivity.class).addFlags(android.content.Intent.FLAG_ACTIVITY_NEW_TASK));waitForIdleSync();runOnMainSync(()->{activity.query.setText("Acid");button(activity.layout,"Search reference").performClick();});waitWorker(activity);require(activity.results.getChildCount()>0,"UI reference results missing");runOnMainSync(()->activity.results.getChildAt(0).performClick());waitWorker(activity);require(activity.dialog!=null&&activity.dialog.isShowing(),"Reference dialog not visible");String[] visible={""};runOnMainSync(()->visible[0]=visibleText(activity.dialog.getWindow().getDecorView()));require(visible[0].contains("Citation identity:")&&visible[0].contains("not cleared"),"Reference provenance missing from visible dialog");put("wiki_dialog",visible[0]);runOnMainSync(()->{activity.dialog.dismiss();activity.city.setText("Mexico City");activity.radius.setText("1");button(activity.layout,"Find city").performClick();});waitWorker(activity);require(activity.results.getChildCount()>0,"City control failed");runOnMainSync(()->activity.results.getChildAt(0).performClick());waitWorker(activity);require(activity.results.getChildCount()>0,"Nearby control failed");runOnMainSync(()->activity.results.getChildAt(0).performClick());waitWorker(activity);require(activity.dialog!=null&&activity.dialog.isShowing(),"Place dialog not visible");runOnMainSync(()->visible[0]=visibleText(activity.dialog.getWindow().getDecorView()));require(visible[0].contains("Routing unavailable")&&visible[0].contains("Source provenance"),"Place provenance/unknowns absent");put("place_dialog",visible[0]);runOnMainSync(()->{activity.dialog.dismiss();button(activity.layout,"Active bulk collections").performClick();});waitWorker(activity);require(activity.dialog.isShowing(),"Collection dialog not visible");runOnMainSync(()->{activity.dialog.getListView().performItemClick(activity.dialog.getListView().getChildAt(0),0,0);activity.dialog.getButton(-1).performClick();});waitWorker(activity);require(!new ScaleLibrary(files).entries().get(0).active,"Actual collection control did not persist disabled state");runOnMainSync(()->button(activity.layout,"Active bulk collections").performClick());waitWorker(activity);runOnMainSync(()->{activity.dialog.getListView().performItemClick(activity.dialog.getListView().getChildAt(0),0,0);activity.dialog.getButton(-1).performClick();});waitWorker(activity);require(new ScaleLibrary(files).entries().get(0).active,"Actual collection control did not restore state");put("active_selection_ui_persisted",true);runOnMainSync(activity::finish);
 }
 else if(mode.equals("negative")){
 byte[] before=java.nio.file.Files.readAllBytes(new File(lib.root,"catalog.json").toPath());String model=ScaleLibrary.hash(new File(files,"model.gguf"),()->false);JSONArray checks=new JSONArray();
 for(String name:new String[]{"corrupt","cancel-before","cancel-during","over-budget"}){byte[] payload=new byte[262144];Arrays.fill(payload,(byte)7);String expected=ScaleLibrary.hex(java.security.MessageDigest.getInstance("SHA-256").digest(payload));JSONObject spec=new JSONObject().put("path","fixture.bin").put("bytes",payload.length).put("sha256",expected);JSONObject m=new JSONObject().put("version",1).put("kind","wiki").put("generation_allowed",false).put("rights_status","constructed integrity fixture, not corpus").put("source_inventory_sha256",expected).put("installed_bytes",payload.length).put("files",new JSONArray().put(spec));if(name.equals("over-budget")){spec.put("bytes",10_000_000_001L);m.put("installed_bytes",10_000_000_001L);}ByteArrayOutputStream bytes=new ByteArrayOutputStream();try(java.util.zip.ZipOutputStream z=new java.util.zip.ZipOutputStream(bytes)){z.putNextEntry(new java.util.zip.ZipEntry("manifest.json"));z.write(m.toString().getBytes(StandardCharsets.UTF_8));z.closeEntry();z.putNextEntry(new java.util.zip.ZipEntry("fixture.bin"));if(name.equals("corrupt"))payload[10]=8;z.write(payload);z.closeEntry();}AtomicInteger calls=new AtomicInteger();long t=SystemClock.elapsedRealtime();try{lib.install(new ByteArrayInputStream(bytes.toByteArray()),()->name.equals("cancel-before")||name.equals("cancel-during")&&calls.incrementAndGet()>4);throw new AssertionError("Negative import admitted: "+name);}catch(IOException expectedError){checks.put(new JSONObject().put("case",name).put("error",expectedError.toString()).put("ms",SystemClock.elapsedRealtime()-t));}require(Arrays.equals(before,java.nio.file.Files.readAllBytes(new File(lib.root,"catalog.json").toPath())),"Failed import changed catalog");require(lib.root.listFiles((d,n)->n.startsWith("pending-")).length==0,"Failed import left staging");}
 File owned=java.nio.file.Files.createTempDirectory(files.toPath(),"scale-regression-").toFile();try{ScaleLibrary retry=new ScaleLibrary(owned);File archive=new File(files,"source-fixture.plscale");put("regression_archive_sha256",ScaleLibrary.hash(archive,()->false));try(InputStream in=new FileInputStream(archive)){try{retry.install(in,()->true);throw new AssertionError("Retry pre-cancel ignored");}catch(InterruptedIOException expected){}}ScaleLibrary.Entry e;try(InputStream in=new FileInputStream(archive)){e=retry.install(in,()->false);}ScaleWiki.Hit h=ScaleWiki.byId(e,"fixture","79780308",()->false);ScaleWiki.read(h,getTargetContext().getCacheDir(),()->false);File block=new File(e.directory,"fixture/articles.blocks");try(RandomAccessFile f=new RandomAccessFile(block,"rw")){int first=f.read();f.seek(0);f.write(first^1);}try{ScaleWiki.read(h,getTargetContext().getCacheDir(),()->false);throw new AssertionError("Corrupt source block accepted");}catch(IOException expected){put("changed_source_block_rejected",expected.toString());}put("same_process_retry",true);}finally{ScaleLibrary.removeTree(owned);}
 require(model.equals(ScaleLibrary.hash(new File(files,"model.gguf"),()->false)),"Saved model changed");put("checks",checks);put("saved_model_sha256",model);put("retained_collections",lib.entries().size());
 }else if(mode.equals("native")){
 File model=new File(files,"model.gguf");String hash=ScaleLibrary.hash(model,()->false);require(hash.equals("74a4da8c9fdbcd15bd1f6d01d621410d31c6fc00986f5eb687824e7b93d7a9db"),"Production model pin");put("model_sha256",hash);put("model_bytes",model.length());put("runtime",NativeRuntime.identity());PackLibrary.Snapshot small=new PackLibrary(files).load();put("small_catalog",small.description());long id=NativeRuntime.create();try{long t=SystemClock.elapsedRealtime();NativeRuntime.load(id,model.getPath().getBytes(StandardCharsets.UTF_8));put("load_ms",SystemClock.elapsedRealtime()-t);put("loaded_memory",memory());for(ScaleLibrary.Entry e:lib.entries())if(e.active&&e.kind().equals("wiki"))put("bulk_hits_while_model_loaded",ScaleWiki.search(e,"Acid",()->false).size());
 AnswerEngine.Generator generator=new AnswerEngine.Generator(){public int run(byte[] p,int limit,NativeRuntime.Sink sink){return NativeRuntime.generateChat(id,EvidencePrompt.SYSTEM.getBytes(StandardCharsets.UTF_8),p,limit,sink);}public int countTokens(byte[] p){return NativeRuntime.countChatTokens(id,EvidencePrompt.SYSTEM.getBytes(StandardCharsets.UTF_8),p);}public int runWithSources(byte[] p,int limit,NativeRuntime.Sink sink,int sources,boolean combined){return NativeRuntime.generateClaims(id,EvidencePrompt.SYSTEM.getBytes(StandardCharsets.UTF_8),p,limit,sink,sources,combined);}};
 String question="Why are headlamps recommended for lighting at night?";ResearchEngine.Result evidence=small.engine.research(question);AnswerEngine.Outcome a=AnswerEngine.answer(question,evidence,generator,x->{},()->false);JSONArray sources=new JSONArray();for(ResearchEngine.Hit h:evidence.hits)sources.put(new JSONObject().put("id",h.passage.id).put("text",h.passage.text).put("url",h.passage.url).put("rights",h.passage.license));put("answer",new JSONObject().put("question",question).put("route",a.kind.toString()).put("invoked",a.invokedModel).put("draft",a.rawDraft).put("rendered",a.text).put("reason",a.reason).put("prompt",a.prompt).put("sources",sources).put("tokens",a.tokens).put("first_token_ms",a.firstTokenMs).put("total_ms",a.totalMs));require(a.invokedModel,"JNI control did not invoke model");NativeRuntime.cancel(id);require(NativeRuntime.generateChat(id,new byte[0],"test".getBytes(StandardCharsets.UTF_8),8,b->{throw new AssertionError("cancel emitted token");})==-1,"Native cancellation");NativeRuntime.reset(id);put("cancel_reset",true);put("combined_memory",memory());}finally{NativeRuntime.close(id);}long reload=NativeRuntime.create();try{NativeRuntime.load(reload,model.getPath().getBytes(StandardCharsets.UTF_8));put("reload",true);}finally{NativeRuntime.close(reload);}
 }
 else if(mode.equals("inspect")){JSONArray queries=new JSONArray();for(ScaleLibrary.Entry e:lib.entries()){require(!e.mayGenerate(),"source rights gate");ScaleLibrary.verifySchema(e.directory,e.manifest,()->false);if(e.kind().equals("wiki")){for(String q:new String[]{"Acid","Cooking","Absolute value","Algae","Transport in Belgium","Binary search","Constitution","Athens"}){long t=SystemClock.elapsedRealtime();List<ScaleWiki.Hit> hits=ScaleWiki.search(e,q,()->false);JSONArray titles=new JSONArray();for(ScaleWiki.Hit h:hits)titles.put(h.title);JSONObject observation=new JSONObject().put("query",q).put("titles",titles).put("ms",SystemClock.elapsedRealtime()-t);if(!hits.isEmpty()){ScaleWiki.Hit h=hits.get(0);ScaleWiki.Read r=ScaleWiki.read(h,getTargetContext().getCacheDir(),()->false);observation.put("source_identity",h.identity()).put("source_preview",r.text.substring(0,Math.min(500,r.text.length()))).put("raw_block_bytes",r.rawBlockBytes);}queries.put(observation);put("wiki_queries",queries);}
 JSONArray absent=new JSONArray();for(String absentQuestion:new String[]{"exact cloud cover here at midnight tonight","restaurants guaranteed open right now","guaranteed current vegan status from missing tags"}){List<ScaleWiki.Hit> related=ScaleWiki.search(e,absentQuestion,()->false);absent.put(new JSONObject().put("question",absentQuestion).put("retrieval_candidates",related.size()).put("generation_allowed",e.mayGenerate()).put("route","browse_only; current availability unknown"));}put("absent_controls",absent);
 JSONArray oversizedRow=NativeIndex.rows(ScaleWiki.database(e,"000_00000").getPath(),"SELECT "+ScaleWiki.COLS+" FROM articles WHERE id=?",new String[]{"79374590"},1,()->false).getJSONArray(0);oversizedRow.put(11,Long.toString(ScaleWiki.MAX_RECORD+1));try{ScaleWiki.read(new ScaleWiki.Hit(e,"000_00000",oversizedRow),getTargetContext().getCacheDir(),()->false);throw new AssertionError("Oversized record admission ignored");}catch(IOException expected){put("oversized_metadata_rejected",expected.toString());}AtomicInteger queryPolls=new AtomicInteger();long cancelledAt=SystemClock.elapsedRealtime();try{NativeIndex.rows(ScaleWiki.database(e,"000_00000").getPath(),"WITH RECURSIVE cnt(x) AS (SELECT 1 UNION ALL SELECT x+1 FROM cnt WHERE x<100000000) SELECT sum(x) FROM cnt",new String[]{},1,()->queryPolls.incrementAndGet()>4);throw new AssertionError("Running index cancellation ignored");}catch(IOException expected){put("running_index_cancel_ms",SystemClock.elapsedRealtime()-cancelledAt);}
 ScaleWiki.Hit large=ScaleWiki.byId(e,"000_00000","79374590",()->false);put("before_oversized",memory());long t=SystemClock.elapsedRealtime();java.util.concurrent.atomic.AtomicBoolean sampling=new java.util.concurrent.atomic.AtomicBoolean(true);long[] peak={0,0,0};Thread sampler=new Thread(()->{while(sampling.get()){Debug.MemoryInfo m=new Debug.MemoryInfo();Debug.getMemoryInfo(m);peak[0]=Math.max(peak[0],m.getTotalPss());peak[1]=Math.max(peak[1],Runtime.getRuntime().totalMemory()-Runtime.getRuntime().freeMemory());peak[2]++;try{Thread.sleep(20);}catch(InterruptedException ignored){break;}}});sampler.start();ScaleWiki.Read r;try{r=ScaleWiki.read(large,getTargetContext().getCacheDir(),()->false);}finally{sampling.set(false);sampler.join();}put("oversized_sampled_peak",new JSONObject().put("pss_kib",peak[0]).put("java_used_bytes",peak[1]).put("samples",peak[2]).put("interval_ms",20));put("oversized",new JSONObject().put("title",large.title).put("raw_block_bytes",r.rawBlockBytes).put("record_bytes",r.recordBytes).put("temporary_bytes",r.temporaryBytes).put("ms",SystemClock.elapsedRealtime()-t).put("memory_after",memory()).put("preview_truncated",r.previewTruncated));require(r.rawBlockBytes>8*1024*1024,"not oversized fixture");AtomicInteger polls=new AtomicInteger();t=SystemClock.elapsedRealtime();try{ScaleWiki.read(large,getTargetContext().getCacheDir(),()->polls.incrementAndGet()>10);throw new AssertionError("read cancellation ignored");}catch(InterruptedIOException expected){put("large_read_cancel_ms",SystemClock.elapsedRealtime()-t);}require(getTargetContext().getCacheDir().listFiles((d,n)->n.startsWith("scale-record-")).length==0,"stale source staging");
 try{NativeIndex.rows(ScaleWiki.database(e,"000_00000").getPath(),"DELETE FROM articles",new String[]{},1,()->false);throw new AssertionError("write accepted");}catch(IOException expected){put("readonly_rejection",expected.toString());}
 }else{JSONArray cities=new JSONArray();for(String name:new String[]{"Auckland","Berlin","Buenos Aires","Cairo","Cape Town","Istanbul","Lagos","London","Los Angeles","Mexico City","Mumbai","Nairobi","New York","Paris","Sao Paulo","Seoul","Singapore","Sydney","Tokyo","Toronto"}){long t=SystemClock.elapsedRealtime();List<ScalePlaces.City> cs=ScalePlaces.cities(e,name,()->false);JSONObject row=new JSONObject().put("query",name).put("city_matches",cs.size());if(!cs.isEmpty()){ScalePlaces.City c=cs.get(0);List<ScalePlaces.Hit> hs=ScalePlaces.nearby(e,c.lat,c.lon,1,null,()->false);row.put("city_id",c.id).put("lat",c.lat).put("lon",c.lon).put("places",hs.size());if(!hs.isEmpty())row.put("source",ScalePlaces.detail(hs.get(0),()->false));}row.put("ms",SystemClock.elapsedRealtime()-t);cities.put(row);put("cities",cities);}ScalePlaces.City c=ScalePlaces.cities(e,"London",()->false).get(0);require(ScalePlaces.nearby(e,c.lat,c.lon,1,"nonexistentcategory300",()->false).isEmpty(),"absent category leaked");put("absent_category","withheld: no matching source category");}}
 Set<String> all=new HashSet<>();for(ScaleLibrary.Entry e:lib.entries())all.add(e.id);lib.select(Collections.emptySet());require(new ScaleLibrary(files).entries().stream().noneMatch(e->e.active),"disabled restart");lib.select(all);require(new ScaleLibrary(files).entries().stream().allMatch(e->e.active),"active restart");put("active_restart_count",all.size());
 }put("after",memory());put("elapsed_ms",SystemClock.elapsedRealtime()-start);put("status","PASS");result.putString("report",report.toString());finish(-1,result);
 }catch(Throwable error){try{put("status","FAIL");put("error",error.toString());}catch(Exception ignored){}result.putString("error",error.toString());finish(1,result);}}
}
